### ISSUE TITLE
Difference between projectRaster and project

### ISSUE THREAD

**Issue by RS-eco** [rspatial/terra#102]
I am currently performing some analysis and have encountered that there is quite a difference in the result between raster::projectRaster() and terra::project(), when projecting a long-lat raster to mollweide equal-area projection. 
See here for a reproducible example:

```{r}
library(raster)
library(terra)


moll <- "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"

r <- raster(ncols=360, nrows=180)
values(r) <- 1:ncell(r)
r

r_moll_raster <- raster::projectRaster(r, crs=moll)
r_moll_raster

r_moll_terra <- terra::project(terra::rast(r), y=moll)
r_moll_terra
```

**Comment by rhijmans** [comment]
If I understand your example well, there are differences because you only supply a `crs` (`y` in terra) argument. You can do that to get a quick result, but this is not something you should do in data analysis. To have control over the output, you should provide a template that specifies the extent and resolution.  Otherwise your intentions are not well defined. If you do that, the difference are very small in this example.
```
x <- rast(r_moll_raster)
r_moll_terra <- terra::project(terra::rast(r), y=x)
dif <- r_moll_terra - x
rdif <- dif / x
plot(rdif)
```

**Comment by RS-eco** [comment]
And for projectRaster() specifying the CRS is sufficient or would I also have to specify the extent and resolution?
And how can I find out the correct extent and resolution if I want to transform for example a global WGS84 layer into an equal-area projection?

**Comment by rhijmans** [comment]
In most cases you transform raster data because you need make one raster dataset `x` match another raster dataset `y`. If that case you can do `z <- project(x, y)`
 
If you do not have a template (other dataset) to begin with, you can do `z <- project(x, crs)` and then manipulate z  to get the template you want.  For example, where possible use whole numbers for the extent and resolution so that you do not have to worry about small differences in the future. Once you have a nice template, you use that.  You can use commands like `dim(z) = c(180, 360)` or `res(z) <- 100000`

There is no "correct" resolution if you go from `lon/lat` to `Mollweide` as you are doing. That is because the resolution of lon/lat data is in degrees, and thus the horizontal resolutions varies (in m) with latitude.  The simplest way to set the resolution of `z` would be to give it same number of rows and columns as `x` (I note that raster in your example is a bit closer to that than terra). Or the same resolution (in m) as `x` at a certain latitude (e.g. 45 degrees). 

I have seen people transform raster data to match vector data they use in their analysis. That is not right, you should make vector data match raster data. However, if your purpose is not analysis but mapping, other considerations apply.  

Despite all this, it would not be a bad thing if `raster` and `terra` did the same thing in your example. The reason for the difference is that in `raster` the extent and resolution is based on code that I wrote, with improvements by others (e.g. https://github.com/rspatial/raster/issues/158); whereas in `terra` the GDAL library takes care of it.  One approach might be preferable than the other, but fundamentally there is no right answer. 

(by the way referring to the lon/lat as "WGS84" is commonly done but not correct. WGS84 is a *datum*, after transforming your data to the Mollweide coordinate references system, you would normally still be using WGS84).

**Comment by mdsumner** [comment]
Oh btw, I have `spex::buffer_extent(x, res)` which I use a lot to get whole numbers (grain) padded out. Long meant to ask to include similar in raster/terra

**Comment by rhijmans** [comment]
Interesting, I would have liked to do `floor(x, res)`  but `floor` does not take additional arguments. 

I think `align(x, y, "out")` does this, but it requires argument `x` to be a `SpatRaster`; so I am thinking of another `align` where argument `y` is numeric.

**Comment by mdsumner** [comment]
Sounds good - I use the pattern *a lot*, raster template objects are super useful and powerful. I for a while tried to overload `%%`  which seemed appropriate for the task but couldn't get it to fly ...

**Comment by rhijmans** [comment]
With [this commit](https://github.com/rspatial/terra/commit/923335266587abe22126baa9ca36afcb455c2dcel) I get:

```
library(terra)
e <- ext(0.1, 2.2, 0, 3)
e
#SpatExtent : 0.1, 2.2, 0, 3 (xmin, xmax, ymin, ymax)

align(e, 2)
#SpatExtent : 0, 4, 0, 4 (xmin, xmax, ymin, ymax)

x <- e %% 2
x
#SpatExtent : 0, 4, 0, 4 (xmin, xmax, ymin, ymax)

x * 2
#SpatExtent : -2, 6, -2, 6 (xmin, xmax, ymin, ymax)

x / 2
#SpatExtent : 1, 3, 1, 3 (xmin, xmax, ymin, ymax)

x + 1
#SpatExtent : -1, 5, -1, 5 (xmin, xmax, ymin, ymax)

x - 1
#SpatExtent : 1, 3, 1, 3 (xmin, xmax, ymin, ymax)
```

**Comment by mdsumner** [comment]
V nice, I will check against my own logic abd tests. I like 'align()' that's good
