### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by rCarto** [rspatial/terra#103]
Hello, 
First of all thank you for your work on `raster` and `terra`!

I have developed a package that imports `terra`: [`maptiles`](https://github.com/riatelab/maptiles).
Trying to get it on CRAN I have some issues with the system requirements of `terra`, I'm asked to declare the minimal version possible of these system requirements.    

* DESCRIPTION says it needs GDAL (>= 3.0.4), GEOS (>= 3.8.0), PROJ (>= 6.3.1)
* README says it needs  GDAL (>= 3.0.0), GEOS (>= 3.3.0) and Proj.4 (>= 6.0.0) (shouldn't it be PROJ here ?)
* In the source code gdal version is tested several times with alternatives for GDAL < 3. 
* And I know for sure that GDAL 2.4.2 is not enough, at least for my use case. 

Furthermore, I understand that `terra` is in beta, a wider question may be "is it too soon to release packages based on terra?"

**Comment by rhijmans** [comment]
I use GDAL (>= 3.0.4), GEOS (>= 3.8.0), PROJ (>= 6.3.1) because that is what you now get on windows.  That is what I use for development and have most confidence in that it works. 

The minimal version that I have tried is: GDAL 2.2.3, GEOS 3.6.2, PROJ 4.9.3 on ubuntu.   
terra builds, checks and installs fine with that system. In other words, the specified system requirements are not enforced. 
However, as you may have seen, that will give you this message 

```
library(terra)
#NOTE: using GDAL version 2.2.3
#For full functionality you need at least version 3.0.4
```

The functionality missing is `project`, `resample` and `as.polygons`. So if that is essential to your package, it must be GDAL 3.04

There have been drastic changes in PROJ  6 (without backwards compatibility), so I am flagging that as well by saying that >= 6 is required. I do not know if there are any, but I just do not want to promise to address issues with older versions.

terra does not yet use GEOS much, so 3.6.2 should probably be fine. 

The testing you refer to is done by a script written for rgdal/sf. Because rgdal has been around for a long time, it supports older GDAL versions. 

The next version of terra won't be beta anymore. I put that message there to discourage dependencies, but I think it is OK now; the interface has been very stable over the past months. And it is of course very nice to see terra being used. It would be great if you can check your package with the terra development version before you submit to CRAN.

**Comment by rCarto** [comment]
Thank you for your response. 

> I do not understand why maptiles specifies SystemRequirements (as there is no src folder, it does not seem that it compile any source code that would use the system libraries). Do you really need to do that? Most packages don't.

Yes you are right, I wrongly assumed a sort of transitivity of system requirements. I will remove the line. 

> The missing functionality is project, resample and as.polygons. So if that is essential to your package, it must be GDAL 3.04

`project` is essential in this case, I've added a control to check the GDAL version and display a warning if GDAL < 3.0.4. 

I think I can close the issue.
