### ISSUE TITLE
Warning message: PROJ: proj_identify: Cannot find proj.db (GDAL error 1)

### ISSUE THREAD

**Issue by Rapsodia86** [rspatial/terra#1032]
After yesterday's update, I am getting that warning whenever loading raster or shapefile or saving to file, etc.

**Comment by rhijmans** [comment]
I think I fixed that with this https://github.com/rspatial/terra/commit/9a9c3e7504afafecf9b006cca6a0b01dd881c0ba

**Comment by Rapsodia86** [comment]
Has that fix been pushed? 
I just downloaded terra dev again and installed it, but the warning is still there. Should I wait till tomorrow?

**Comment by rhijmans** [comment]
If it had not been pushed it would not exist on this site.  Do you install from source (or from R-universe)?  What OS?

**Comment by Rapsodia86** [comment]
Win10; from here: install.packages('terra', repos='https://rspatial.r-universe.dev')

**Comment by rhijmans** [comment]
With R-Universe there can be a delay of a couple of hours before the package gets built. But in this case that is not the issue; because it was last build with that push. But somehow the build failed for windows (click on the red question mark on https://rspatial.r-universe.dev/terra  ). I does not seem related to anything I can do, and I would hope this will resolve itself.

**Comment by Rapsodia86** [comment]
I see that failure https://github.com/r-universe/rspatial/actions/runs/4255034198

Ok, will wait then! Should I be worried about that warning now?

**Comment by rhijmans** [comment]
All looking good now.

**Comment by Rapsodia86** [comment]
Yes, no more warnings! Thank you:)

**Comment by Rapsodia86** [comment]
Hello! 
I have installed today the recent dev terra 1.7-41 and the warning showed up again. I had it uninstalled and installed the regular terra 1.7-39 from CRAN and no more issues.
