### ISSUE TITLE
legend() and inset() now partially outside the map window

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1053]
This didn't happen before, but (at least on Linux Mint 21.1 Cinnamon) with the latest CRAN version of terra (1.7-18), a `legend()` added to a keyword-specified location appears cut off, or even doesn't appear at all if 'cex' is not large enough.  The legend now seems to be aligned to the "topleft" of the plotting device, or to the map window including the axis labels and colour keys, rather than to the actual map window as it used to be.

```
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v)
plot(centroids(v), add = TRUE)
legend("topleft", legend = "centroids", pch = 20)
legend("topright", legend = "centroids", pch = 20)
legend("bottomleft", legend = "centroids", pch = 20)
legend("bottomright", legend = "centroids", pch = 20)
```
![image](https://user-images.githubusercontent.com/12085508/223442220-d800074f-a856-4956-aaa4-954497d8d527.png)

The same is now happening with `inset()` too:

```
x <- v[v$NAME_2 == "Diekirch", ]
plot(x, density=10, col="blue")
inset(v)
inset(v, loc = "topright")
```

**Comment by rhijmans** [comment]
I fixed the inset. The custom legend is trickier.  The underlying problem is that I changed how the axes are drawn. They are now drawn snugly around the maps, where they should be. Previously, they would fill the entire "plotting region" creating a lot of odd white space if the aspect of the map was different from that of the plotting space. But `legend` does not know about that, and I do not think there is a way to tell it. 

The solution I propose is to use a new function that I just added:  `add_legend` .  It is a wrapper around `legend` with the only difference being that it fixes the legend placement if a keyword is used to position it. See below:

```
library(terra)
v <- vect(system.file("ex/lux.shp", package="terra"))
plot(v)
points(centroids(v), col="red")
legend("topleft", legend = "centroids", pch = 20, xpd=NA, bg="white", col="red")
add_legend("topright", legend = "centroids", pch = 20, col="red")
inset(v, loc="bottomright")
```
 
![luxleg](https://user-images.githubusercontent.com/11481397/223518045-6250c802-8805-4210-b3ff-4835e7f1eb92.png)

**Comment by rhijmans** [comment]
Closed with the wrong commit. Either way, I believe this has been resolved.

**Comment by Schuch666** [comment]
Hi @rhijmans , 
I know this is a old closed issue, but I think it is related to my problem.

I'm trying to include some custom axis over a plot from terra package, but the axis are on a wrong possition (the position controled by line argument on the axis function from graphics), there is another way or another function that I can use instead of axis?

Currently I'm passing some stuff to fun argument of terra::plot

Another issue is: I'm also trying to add a lat-lon grid (graticule style) and the end of the lines are outside the ploting are, there is a way to control this? (it is also passed to fun argument of terra::plot)

Thank you

**Comment by rhijmans** [comment]
@Schuch666: Can you please open a new issue(s) and include a simple example.  It is too difficult for me to properly address issues without a proper context. And closed issues tend to fall by the wayside. Alsp, perhaps see `terra::graticule`

**Comment by Schuch666** [comment]
@rhijmans ok, I have advanced a bit, I will post a reproducible code later (for now it is inside a unfinished function inside a package I'm working on)

`terra::graticule` is working for my plot function!

**Comment by Schuch666** [comment]
@rhijmans thank you
