### ISSUE TITLE
Terminal error generated from 'project' command

### ISSUE THREAD

**Issue by dtguerena** [rspatial/terra#110]
Recently when I execute the 'project' command in terra it results in a terminal error. I have not yet been able to circumvent this error.

**Comment by rhijmans** [comment]
Hi David, can you provide some more info though? What is your OS and version of terra? What is the transformation you are doing (can you `show(x)` the input?

**Comment by dtguerena** [comment]
Running mac Catalina (10.15.6) and terra_0.9-8. 

`utm <- "+proj=utm +zone=37 +datum=WGS84 +units=m +no_defs "
wk <- vect("./westKenya.shp")
wk <- project(wk, utm)
[westKenya.zip](https://github.com/rspatial/terra/files/5668151/westKenya.zip)
`

A few days ago this error was not present

**Comment by rhijmans** [comment]
This works fine for me on win 10 and Catalina with the CRAN and devel versions.  Do you get any messages in the terminal? Can you run this after setting `gdal_warnings(1)` 
Given that something changed, it is likely because of some other installation changing something. Can you re-install terra and try again?
