### ISSUE TITLE
Why file extensions automatically recognized by writeRast are not those of the data file?

### ISSUE THREAD

**Issue by jldupouey** [rspatial/terra#116]
For most raster file formats (Gtiff, netCDF, EHdr, ENVI, SAGA, RST, AAIGrid, BMP), the file extension automatically recognized by writeRaster is that of the main data file, containing the raster values (.tif or .tiff, .nc, .flt, .envi, .sdat, .rst, .asc and .bmp, respectively). But for two others (HFA, RRASTER), this is not the case. The automatically recognized file extension is that of a metafile (.img and .grd, respectively). Why not choose the extension of the main data file (.ige, .gri)? It would be more consistent and easy to grasp for the user. Is it coming from GDAL?

**Comment by rhijmans** [comment]
Gtiff, netCDF,  AAIGrid, BMP HFA only consist of one file (not counting any `.aux.xml` that GDAL made add to enrich them.

Both files are recognized for SAGA (but it only works well for one, so an error is given for the other)

EHdr, ENVI have two files, one of which has extension ".hdr" which is very common and not useful for guessing the format. 

I used RST and GRD because that is what they are referred to in the software they were developed in, but I have added rdc, gri. I think this also holds for .img. It can also be a single file (if it is small enough) and have .ige an additional file, but I have added it as well; as it apparently you also just have an ige
