### ISSUE TITLE
CRAN checks failing for package depending on terra and raster

### ISSUE THREAD

**Issue by see24** [rspatial/terra#1200]
I am seeing an error that terra can't be installed in [GitHub Actions](https://github.com/LandSciTech/roads/actions/runs/5359411565/jobs/9722968732) for my roads package  and also in the[ CRAN checks](https://cran.r-project.org/web/checks/check_results_roads.html). I wanted to resubmit the roads package to CRAN to fix [#28](https://github.com/LandSciTech/roads/issues/28) but I don't think they will accept it while it is not passing these checks. 

Not sure what the link is between the two failures since one is Ubuntu and the others are Debian but I am hoping you will have more insight.

**Comment by rhijmans** [comment]
The github actions problem is due to a problem with installing on OSX. That has been resolved (and CRAN does not check submitted packages on OSX). The other CRAN issues were because of a bug fix in R-devel that broke terra. This has also been resolved (with today's emergency update because that indeed broke a lot of CRAN). There should now not be a problem submitting to CRAN
