### ISSUE TITLE
"band" argument for terra::rast and speed difference between raster and terra

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#123]
I have a big NetCDF file:

```
the_ras <- paste(tempdir(), "/vstm.1999.nc", sep = "")

utils::download.file("ftp://ftp.cdc.noaa.gov/Datasets/NARR/Dailies/monolevel/vstm.1999.nc",
                     the_ras, 
                     method = "auto", 
                     mode = "wb", 
                     cacheOK = TRUE, 
                     extra = getOption("download.file.extra"))
```

The raster as 365 layers (bands) but I want to load only one.  In raster, I would do:

`raster::raster(the_ras, band=3)`

While with terra It seems the band argument isn't available so I need to do:

`terra::rast(the_ras)[[3]]`

Raster is more then 4x faster at doing this task:

```
microbenchmark::microbenchmark(
   raster_package = raster::raster(the_ras, band=3),
   terra_package  = terra::rast(the_ras)[[3]],
   times = 1000
 )
Unit: milliseconds
           expr     min       lq    mean   median        uq      max neval
 raster_package 15.4620 16.62595 22.3064 18.46775  26.93775  82.4528  1000
  terra_package 73.5444 76.79960 99.9023 83.82715 124.03820 265.1659  1000
```

Actually, even without the `band` argument, raster is faster than terra for reading my file:

```
microbenchmark::microbenchmark(
   raster_package = raster::stack(the_ras)[[3]],
   terra_package  = terra::rast(the_ras)[[3]],
   times = 1000
 )
Unit: milliseconds
           expr     min       lq      mean   median        uq      max neval
 raster_package 39.0382 42.66380  62.03106  64.6329  72.90345 220.9013  1000
  terra_package 72.8468 76.86945 104.99744 116.7893 124.16910 181.0366  1000
```

It's not a big deal, but in my case, considering I have thousands of layers to read, the gain could be substantial.  I wanted to post it here in case it's an easy fix to had a `band` argument to the `rast` function and to document the situation.  Feel free to close this issue if your don't find this relevant.  Thanks.

**Comment by rhijmans** [comment]
There are two issues here. 

1) should `rast` have a `band` ( I would probably call it layer) argument? 
This argument is really important when creating a `RasterLayer` from a multi-band file with `raster::raster`. In `terra` we have `rast` which is essentially the same as `raster::brick` (that does not have a `band` argument either).  But I could add it as a convenience.

2) ncdf speed
`raster` directly uses the ncdf library (via `ncdf4`). `terra` uses GDAL, and that is much slower. `terra` has a writeCDF method that does not use GDAL; but to not use GDAL for reading would entail a lot of work. I would eventually do that because GDAL is just too slow. However the new GDAL [multidimensional arrays](https://gdal.org/development/rfc/rfc75_multidimensional_arrays.html#:~:text=Multidimensional%20arrays%20(also%20known%20as,is%20however%20strongly%202D%20oriented.) may be much faster. These are implemented in GDAL 3.1. With windows we are at GDAL 3.0.4; and we may get there soon. Debian/Ubuntu are always years behind, so that may also be a consideration.

**Comment by BastienFR** [comment]
Thanks for the clear explanation. As I said in my question, it's not a deal breaker as my code works well regardless.  I just wanted to point this situation out.  Now I let you decide if it's relevant or not to put effort into it.  Feel free to close this issue.  

As a side note (I know I should not pollute that thread but it's worth it), I started the switch from raster to terra and so far I'm delighted.  You did an amazing job and the package works great.  Thank you very much for your hard work, it's much appreciated.

**Comment by rhijmans** [comment]
Thank you for your kind words and encouragement.
