### ISSUE TITLE
How to reasonably install this within a CI runner (with renv)?

### ISSUE THREAD

**Issue by black-snow** [rspatial/terra#1253]
Hi,

I found [this](https://github.com/r-spatial/sf/issues/1894#issuecomment-1120383916), which is somewhat related.

I'd like to build a package depending on `terra` and using `renv` for all platforms. While installing `libgdal-dev libudunits2-dev` suffices on Linux, installing on macOS apparently requires some extra mile to go (`install.packages("terra", type = "source", configure.args = "--with-proj-lib=$(brew --prefix)/lib/")` after installing `gdal` via homebrew).

Now, I don't see how to do this when using `renv` and the `r-lib/actions/setup-renv@v2` GitHub Action. In theory, I should be able to install `renv`, then do the above mentioned `install.packages` after activating `renv` on macOS only and then `renv::restore()`. But, imho, the action does all of that in one go and I do not really feel like bisecting it and doing it by myself just to patch in a way to install `terra` on macOS ...

Is there any obvious way to do this, which I don't see yet? I could probably just copy all required files from the brew path over to where terra expects them.

I also wonder why, apprently, [it just worked](https://github.com/haganjam/InvTraitR/actions/runs/5770838637/job/15644228917) without any extra installation steps on macOS. I see `pkg-config` but not `gdal` being [preinstalled](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md).

I don't have a mac to give it a spin myself.

**Comment by rhijmans** [comment]
I am rather ignorant about such matters. Does the file below help in any way?
https://github.com/rspatial/terra/blob/master/.github/workflows/pkgdown.yml

**Comment by brownag** [comment]
> I also wonder why, apprently, [it just worked](https://github.com/haganjam/InvTraitR/actions/runs/5770838637/job/15644228917) without any extra installation steps on macOS. 

The macOS binaries that CRAN builds contain the /gdal folder: https://cran.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3/terra_1.7-39.tgz  If you look at the setup you see it is installing the binary terra 1.7-39 from CRAN.

The binary "just works" as long as the latest available version of the package has binaries built, and you are running R-devel, release or old release. If not, then the install method used, and available dependencies, will affect your successful install. To build from source you will, I think, need a `brew install gdal` or similar in your CI for macOS e.g.

```yaml
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gdal
```

I think with the older version of setup-r-dependencies the latest version of a CRAN package was installed (regardless if compilation from source was required). Now you need to force upgrade to the pak lockfile, so CIs breaking because binaries aren't available might be less common than it used to be? I also don't have a mac so my experience is limited to messing around in GH Actions.

**Comment by black-snow** [comment]
Thanks for your replies. I guess I'll go with "it just works" for now - until it does no longer.
