### ISSUE TITLE
network access blocks loading terra in webR / r-wasm

### ISSUE THREAD

**Issue by edzer** [rspatial/terra#1259]
George Stagg reported they have a new WebAssembly version of webR / r-wasm running, and they managed to compile sf and terra, but where sf loads, terra currently doesn't. See discussion here: https://mastodon.social/@gws@mstdn.social/110909452967222064:

> @krzysztof_dyba @edzer It looks like terra crashes trying to call `proj_context_set_enable_network()`. Raw network access is unfortunately not available in browser-based Wasm. I'll look into it, perhaps terra can be tweaked to avoid networking under webR.

`sf` by default has network access off:
```
> sf_proj_network()
[1] FALSE
```

**Comment by georgestagg** [comment]
Just a quick note to add that simply changing the arguments to `proj_context_set_enable_network()` so that the default is "off" does not solve the problem of loading terra under webR. The library function itself is unavailable for use.

So, IMO this is not really an issue with _terra_, but with webR's Wasm build of PROJ. It is absolutely reasonable for terra to assume this function exists and can be used. Since network access under Wasm is not available, our build of PROJ will likely require further patching on our end to handle the problem better.

In any case, if terra _did_ want to work around the problem despite the above, it may be possible to simply gate the calls around an `#ifndef` so that they're avoided when compiling for Wasm using Emscripten. Though, I can't say for sure what other effects that might have if terra assumes network access is available.

```c
#ifndef __EMSCRIPTEN__
	proj_context_set_enable_network(PJ_DEFAULT_CTX, 1);
#endif
```
