### ISSUE TITLE
Created rasters do not have a datatype

### ISSUE THREAD

**Issue by kevinwolz** [rspatial/terra#1300]
Here I create two simple rasters - one with integer values and one with float values.
```
library(terra) # version 1.7-46
r.int <- rast(matrix(rep(as.integer(1), 10000), nrow = 100))
r.flt <- rast(matrix(rep(-100000.000001, 10000), nrow = 100))
```

Neither object has a datatype associated with it.
```
datatype(r.int)
# ""
datatype(r.flt)
# ""
```

If I write these object to disk with `datatype` specified and then read them back in again....
```
name.int <- "test_INT1U.tif"
writeRaster(r.int, name.int, datatype = "INT1U", overwrite = TRUE)
r.in.int <- rast(name.int)

name.flt <- "test_FLT4S.tif"
writeRaster(r.flt, name.flt, datatype = "FLT4S", overwrite = TRUE)
r.in.flt <- rast(name.flt)
```

...they now have a `datatype` associated with them:
```
datatype(r.in.flt)
# "FLT4S"
datatype(r.in.int)
# "INT1U"
```

And the corresponding file sizes show a correct reduction in size for the integer datatype:
```
file.size(name.flt)
# 2077
file.size(name.int)
# 834
```

However, all objects (pre- and post-writing to disk) supposedly have the same size in memory:
```
purrr::map_dbl(list(r.int, r.flt, r.in.int, r.in.flt), object.size)
# 1304 1304 1304 1304
```

1. Why do `r.int` and `r.flt` not have an associated `datatype`?
2. Is it possible to set to set the `datatype` of these SpatRasters in  R directly? How? Or is the only way to do this with `writeRaster()`? It seems that `writeRaster()` does sometimes write raster out with different `datatype` encodings based on what it sees in the SpatRaster, so maybe there is a way to implement this "guessing" process in `rast()` out of the gate?
3. It seems that `object.size()` is actually not useful for SpatRasters. Is there a better way to compare memory use across these various raster types?
4. Does the `datatype` of the raster actually impact memory size or processing speed of various actions in R (e.g. `crop`, `mask`, `aggregate`, `mosaic`, etc.)? Or is `datatype` only relevant to raster file size on disk?

All of these questions are related to the goal of speeding up processing time in my analysis. Currently I'm working with raster that contain float values. I'm wondering if everything will run faster if I transform the data first to integer values and an integer encoding, but it seems like there is not way to set or asses the `datatype` of a raster unless you write it to disk first.

**Comment by kadyb** [comment]
I believe `datatype()` only works for rasters saved on disk. If you want to check the data type of `SpatRaster` object, you should use `is.bool()`, `is.int()` or `is.factor()` (but you must convert first or create with this type). See documentation [here](https://rspatial.github.io/terra/reference/is.bool.html). However, `terra()` always(?) uses the float data type for calculations and there is generally nothing you can do.

`object.size()` does not give an actual value of how much raster takes up memory, because it refers to C++ pointer. To calculate how much it will take in memory, generally multiply the number of columns by the number of rows and the number of layers and 8 (for double) or 4 (for integer). See also [mem_info()](https://rspatial.github.io/terra/reference/mem.html) function and `needed` attribute.

If you want to read data as integer into R, it's probably best to use [gdalraster](https://github.com/USDAForestService/gdalraster/). But the main question is what the performance benefits will be? If the performance is not sufficient, maybe you should also test SAGA or GRASS?

**Comment by rhijmans** [comment]
Since this is not an "issue" it is probably more useful to discuss this here:

https://stackoverflow.com/questions/77205302/controlling-terra-spatraster-size-in-memory/77212273#77212273

**Comment by kadyb** [comment]
Maybe we can improve the documentation? I mean at least:
1. Add a reference to `as.bool()` to `datatype()` docs with a note that it is used to check the type of the raster values.
2. In `datatype()` write that it only checks the data type of rasters saved on disk.

**Comment by rhijmans** [comment]
Thanks. I split the datatype from the geomtype help and I expanded the description a bit. Feel free to add more.
