### ISSUE TITLE
`layerCor()` $mean could be a single column

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#1323]
`layerCor()` with the default arguments returns a square matrix of correlations and a square matrix of means. Is there a reason for the latter to be a square matrix, rather than just a one-column matrix or a named vector? The columns are confusing this way, and the rows have redundant info. Cheers!

**Comment by rhijmans** [comment]
Thanks. I do not know what the reason for this was, if there was any. So I have made it the same as for the other values of "fun"

**Comment by ailich** [comment]
@rhijmans, following up on a comment in #1056 where using `fun="weighted.cov"` returns a vector of weighted means rather than a matrix of paired weighted means. I mentioned this was inconsistent with whar `fun="pearson"` returns, but I just realized that this also provides an incorrect result in the presence of `NA` values regardless of whether a newer or older version of `terra` is used. I suspect this issue is related to something like using the number of cells in the raster as the number of observations in the calculation rather than the number of cells that are not `NA`.

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.1
#> terra 1.7.47

r<- rast(volcano, 
         extent= ext(2667400, 2667400 + ncol(volcano)*10, 
                     6478700, 6478700 + nrow(volcano)*10), 
         crs = "EPSG:27200")
names(r)<- "elev"

slp<- terrain(r, v="slope", unit="degrees")
asp<- terrain(r, v="aspect", unit="degrees")
slp[is.na(values(slp))]<- global(slp, mean, na.rm=TRUE) #Fill NA's
asp[is.na(values(asp))]<- global(asp, mean, na.rm=TRUE) #Fill NA's

set.seed(5)
w<- rast(r)
values(w)<- sample(0:100, replace = TRUE, size = ncell(w)) #Weights layer

# Without NA's the value returned by layerCor returns the global weighted mean
layerCor(c(r, slp, asp), "weighted.cov", w=w, na.rm=TRUE)$weighted_mean
#>      elev     slope    aspect 
#> 130.16713  14.92675 179.11686

weighted.mean(values(r), w = values(w), na.rm=TRUE)
#> [1] 130.1671
weighted.mean(values(slp), w = values(w), na.rm=TRUE)
#> [1] 14.92675
weighted.mean(values(asp), w = values(w), na.rm=TRUE)
#> [1] 179.1169

#Introduce NA's
set.seed(5)
values(r)[sample(1:ncell(r), size = 100)]<- NA
values(slp)[sample(1:ncell(slp), size = 1000)]<- NA
values(asp)[sample(1:ncell(asp), size = 500)]<- NA

# With NA's the value returned by layerCor does NOT match the global weighted mean
layerCor(c(r, slp, asp), "weighted.cov", w=w, na.rm=TRUE)$weighted_mean
#>      elev     slope    aspect 
#> 127.99890  12.16293 161.46173

weighted.mean(values(r), w = values(w), na.rm=TRUE)
#> [1] 130.187
weighted.mean(values(slp), w = values(w), na.rm=TRUE)
#> [1] 14.99564
weighted.mean(values(asp), w = values(w), na.rm=TRUE)
#> [1] 178.3456
```

<sup>Created on 2023-10-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ailich** [comment]
Actually, this is not related to counting the number of non-NA cells. This line [here](https://github.com/rspatial/terra/blob/f66a0a1bc61a9a96020738e763c4900e8afabfcd/R/layerCor.R#L145C1-L145C77) is just calculating the row-wise mean of the pairwise means since an apply statment was added in commit 5ac826e. This is only equal to the global mean if all layers have NA's for the exact same cells (i.e. all values in a row are equal).

``` r
library(terra)
#> Warning: package 'terra' was built under R version 4.3.1
#> terra 1.7.47

r<- rast(volcano, 
         extent= ext(2667400, 2667400 + ncol(volcano)*10, 
                     6478700, 6478700 + nrow(volcano)*10), 
         crs = "EPSG:27200")
names(r)<- "elev"

slp<- terrain(r, v="slope", unit="degrees")
asp<- terrain(r, v="aspect", unit="degrees")


set.seed(5)
idx<- sample(1:ncell(slp), size = 1000)
values(r)[idx]<- NA
values(slp)[idx]<- NA
values(asp)[idx]<- NA

global(c(r,slp,asp), fun=mean, na.rm=TRUE)
#>            mean
#> elev   130.0878
#> slope   14.9462
#> aspect 179.7868
rowMeans(layerCor(c(r,slp,asp), fun="pearson", na.rm=TRUE)$mean, na.rm = TRUE)
#>     elev    slope   aspect 
#> 131.5401  14.9462 179.7868
```

<sup>Created on 2023-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rhijmans** [comment]
Thanks a lot for that Alex. I think it now works as it should, and we are keeping the matrix with means as the mean for a layer can change depending on the NAs in the other layers.

**Comment by ailich** [comment]
Awesome. Seems to be working great now! I put in a minor pull request to clarify the documentation.
