### ISSUE TITLE
terra::distance with signature 'SpatRaster,missing' does not work properly

### ISSUE THREAD

**Issue by h2ugo24** [rspatial/terra#1400]
Hi. I am using terra version 1.7.65 on Windows 11.

I've used terra::distance function before with signature "Spatraster,missing" and the output was a a spatraster with distance values estimated for each cell in relation to a target value. But it appears that's not working  anymore. Not sure if I'm missing something. See the example below:

 r <- rast (ncols=160, nrows=120, crs="+proj=longlat +datum=WGS84", res=0.25, xmin=-40, xmax=0, ymin=20, ymax=50)
values(r) <- 1:ncell(r)
test=distance(r, target=1000)
plot(test)

![terra distance example](https://github.com/rspatial/terra/assets/118903772/b5f678ca-7cee-4b63-bb77-ffeaa7596f91)

Thanks in advance!!

**Comment by AMBarbosa** [comment]
This result is indeed a bit puzzling, but the help file does say that "_this method computes the distance, **for all cells that are NA** in SpatRaster x to the nearest cell that is not NA (or other values, see arguments "target" and "exclude")_". If you first convert to NA the cells for which you wish to compute the distance, it works as expected:
```
r[r != 1000] <- NA
test <- distance(r)
plot(test)
```

**Comment by h2ugo24** [comment]
Previously i didn't have to do this step, but all is working well now. Thank you! =)

**Comment by rhijmans** [comment]
Your example seems to work fine. You are asking for the distance from cells that have the value 1000 (target) to cells that are not NA. You only have one cells that has the value of 1000 so that is the only distance you get.  To see this in action with more cells:
 
```
x <- classify(r, cbind(5000, 15000, 1000))
test <- distance(x, target=1000)
```

If you wanted the inverse, that is, the distance of all cells that are not NA to the cells that have value 1000 (which is what @AMBarbosa shows)

```
test <- distance( r != 1000,  target=TRUE)
```
