### ISSUE TITLE
Unexpected focal behavior

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#1402]
I assume this is not a big issue, but I found it unexpected (and was unable to understood it). 
In short, the focal function seems to be going through one of the focal cells twice. 
The result of the focal function is, however, correct:

``` r
library(terra)
#> terra 1.7.69
r = rast(matrix(1:12, ncol = 3, byrow = TRUE))
plot(r)

my_fun = function(x){
  print(x)
  x
}

a = focal(r, fun = my_fun, w = 1)
#> [1] 4
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
#> [1] 5
#> [1] 6
#> [1] 7
#> [1] 8
#> [1] 9
#> [1] 10
#> [1] 11
#> [1] 12
plot(a)
```

![](https://i.imgur.com/2YOnC6L.png)

**Comment by rhijmans** [comment]
Because you provide a custom function, `focal` needs to find out what the shape is of the values returned by that function. It takes some values from the middle of the raster to figure that out; in this case that is only one value because the raster is so small.  

Is there a reason why you would use w=1? I am inclined to return an error when "w=1" or a 1x1 matrix is used because in that case you are not doing a focal operation. I could pass this on to `app` instead, but an error (perhaps saying "see app") seems more appropriate.

**Comment by Nowosad** [comment]
Dear @rhijmans -- thank you for your explanation. I think that no action is needed.

I am just working on a fairly complex focal operation, and I spent a long time yesterday trying to understand why it prints one value too many. I decided to open this issue to save some time for other people in the same position.

(I only used `w=1` in this example, as it prints only one value per loop, and thus it clearly shows the issue; however, the same effect is visible for larger windows (e.g., `w=3`))
