### ISSUE TITLE
writeRaster wopt examples in man

### ISSUE THREAD

**Issue by MatMatt** [rspatial/terra#141]
Hi,
You  might consider to add a example on how to use the `wopt` argument. I made it wrong without any warning from writeRaster side (i.e. I did `writeRaster(r,overwrite=T,filename=tmpf, gdal=c("COMPRESS=LZW", "TFW=YES"), datatype='INT1U')`. Such an example may helps avoiding such errors. 
 

library(terra)

r <- rast()
values(r) <- sample(0:100,size = ncell(r),replace = TRUE)
plot(r)

tmpf <- paste0(tempdir(),"/deleteme.tif")

writeRaster(r,tmpf)
file.size(tmpf)

writeRaster(r,overwrite=T,filename=tmpf,wopt=list(gdal=c("COMPRESS=LZW", "TFW=YES","of=COG")))
file.size(tmpf)

writeRaster(r,overwrite=T,filename=tmpf,wopt=list(gdal=c("COMPRESS=LZW", "TFW=YES","of=COG"), datatype='INT1U'))
file.size(tmpf)

unlink(tmpf)

**Comment by rhijmans** [comment]
Instead of documenting I have removed `wopt` from `writerRaster` and will remove them from other methods as well, except where the additional arguments need to be passed to another function, as in, e.g., `terra::predict`. That was the reason for `wopt` to distinguish beteween different groups of additional arguments, but there is no need for it in most methods.

**Comment by rhijmans** [comment]
And I have added the example
