### ISSUE TITLE
In `spatSample`, should the default be `replace = TRUE` when `method = "weights"` ?

### ISSUE THREAD

**Issue by frousseu** [rspatial/terra#1565]
Hi!

When using `method = "weights"` in spatSample, the default `replace = FALSE` has the consequence that non 0 cells will be filled if the size asked is larger than the number of non 0 cells, losing the proportionality between the weights and the density of points generated. I think it would make more sense to have `replace = TRUE` as the default when `method = "weights"`. In fact, I have a hard time finding a use for `replace = FALSE` when the weight method is used.  Below is an example with the first case showing a lack of proportionality and the second case showing what I think should be the default.

Thanks!
François

```r
library(terra)
library(sf)

set.seed(123)
r <- rast(res = 2, extent = c(0, 10, 0, 10))
v <- sample(c(0, 1, 10), ncell(r), replace = TRUE)
r <- setValues(r, v)
plot(r)

ss <- spatSample(r, size = 25, method = "weights", as.points = TRUE, replace = FALSE) |> 
  st_as_sf() |> 
  st_jitter(amount = 0.2) |> 
  st_geometry()

par(mfrow = c(1, 2))
plot(r)
plot(ss, add = TRUE)
length(ss)

ss <- spatSample(r, size = 25, method = "weights", as.points = TRUE, replace = TRUE) |> 
  st_as_sf() |> 
  st_jitter(amount = 0.2) |> 
  st_geometry()

plot(r)
plot(ss, add = TRUE)
length(ss)
```

**Comment by rhijmans** [comment]
Thank you for this. 

Your example is the extreme situation because there are only very few cells. If you subdivide `r` like this

```
r <- disagg(r, 10)
```

`spatSample` works as expected when using "replace=FALSE"

I could set the default value of replace to "(method=="weights")" but I think that would not be easily understood by many, so I am opting to leave this as is. Also because I think that there are cases when you want to use replace=FALSE, even if that means that the weights become imbalanced.
