### ISSUE TITLE
Install terra error

### ISSUE THREAD

**Issue by honghh2018** [rspatial/terra#1595]
Hi, developer, 
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... ERROR 6: Unable to load PROJ.4 library (libproj.so), creation of OGRCoordinateTransformation failed.
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘terra’
* removing ‘/share/apps/R/R-4.1.2-4/lib64/R/library/terra’
* restoring previous ‘/share/apps/R/R-4.1.2-4/lib64/R/library/terra’

The downloaded source packages are in
	‘/tmp/RtmpoXePYx/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("terra") :
  installation of package ‘terra’ had non-zero exit status
> system("gdal-config --version")
2.4.0
> system("proj")
Rel. 8.1.1, September 1st, 2021
usage: proj [-bdeEfiIlmorsStTvVwW [args]] [+opt[=arg] ...] [file ...]

I had already install the proj 8.1.1  and gdal in /usr/local    ,
and then put the lib in LD_LIBRARY_PATH
but it still getting error when install  terra 
Cento7.9

how to fix this error when install the package

Best,
hanhuihong

**Comment by rhijmans** [comment]
The problem is somewhat clear 

> Unable to load PROJ.4 library (libproj.so), creation of OGRCoordinateTransformation failed.

But I do not know why that happens. My best guess is that you have installed your own PROJ while there is another on the system. That often leads to this type of conflicts. Unfortunately, I am not a specialist in these matters and cannot provide further help. It would be good to also try installing "sf". If that has the same problem we know that it is not "terra" specific.
