### ISSUE TITLE
Unexpected behaviour of `tapp(x, "doy")` when dealing with leap years

### ISSUE THREAD

**Issue by stschl** [rspatial/terra#1645]
An unexpected behaviour of `tapp(x, "doy")` has been encountered when `x` is a SpatRaster spanning leap and non-leap years. For example, consider the following:

```r
r <- rast(nc = 5, nr = 5, nlyrs = 365+366, vals = 1)
time(r) <- c(seq(as.Date("2003-01-01"), by = "days", len = 365),
             seq(as.Date("2004-01-01"), by = "days", len = 366))

res <- tapp(r, "doy", fun = length)
tail(global(res))

#        mean
# doy_361    2
# doy_362    2
# doy_363    2
# doy_364    2
# doy_365    2
# doy_366    1
```

For each DOY, two values are used in `fun`, except obviously for DOY 366. This means that 2003-03-01 and 2004-02-29 are together input to `fun`, 2003-03-02 and 2004-03-01, and so forth. This is not the expected behaviour, e.g. when computing a daily climatology.

Would it be possible to for example introduce an option `"doy365"` or similar that addresses this problem?

```
packageVersion("terra")
[1] ‘1.7.83’
terra::gdal(lib="all")
    gdal     proj     geos 
 "3.8.4"  "9.3.1" "3.12.1" 
```

**Comment by rhijmans** [comment]
> This is not the expected behaviour, e.g. when computing a daily climatology.

Maybe, but it is expected behaviour when using DOY. I do not think there is a straightforward solution.  Since the leap date Feb 29 is arbitrary you could argue that this behaviour is fine (you are simply using Dec 32 instead of Feb 29 as leap date).

If you want something else you can implement that relatively easily. For example, to keep the Feb 29s together, you could do

```
library(terra)
r <- rast(nc = 5, nr = 5, nlyrs = 365+366, vals = 1) 
time(r) <- seq(as.Date("2003-01-01"), as.Date("2004-12-31"), 1)
index <- substr(time(r), 6, 10)
res <- tapp(r, index, fun = length)
tail(global(res))
#       mean
#X12.27    2
#X12.28    2
#X12.29    2
#X12.30    2
#X12.31    2
#X02.29    1
```

If you wanted to, equally arbitrary, combine 28 and 29 Feb, you could do that like this

```
index[index == "02-29"] <- "02-28"
res <- tapp(r, index, fun = length)
global(res)[58:60, ,drop=FALSE]
#       mean
#X02.27    2
#X02.28    3
#X03.01    2
```

Since I think there is no "correct" solution that is objectively better than what you get with "doy", so I will leave it to you to decide how to do this. Unless, perhaps, there is a clear (ISO, WMO?) "standard" that you can point to.
