### ISSUE TITLE
expanse on vect seems to compute wrong area/omit polygons?

### ISSUE THREAD

**Issue by MatthieuStigler** [rspatial/terra#1665]
I have a strange (multi) polygon vector  for which terra seems to be omitting one of the polygons? I can see that when computing the area with `expanse` or when plotting (commented in output below)...

Strangely, when exporting the polygin as `shp` and re-reading, the output looks correct?

Thanks!

``` r
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.0; sf_use_s2() is TRUE
library(terra)
#> terra 1.7.83

## download from github issue page
tmp_file <- tempfile()
tmp_dir <- tempdir()
download.file("https://github.com/user-attachments/files/18053467/poly_weird.zip",
              tmp_file)
unzip(tmp_file, exdir = tmp_dir)



conc_prob_sf <- readRDS(file.path(tmp_dir, "poly_weird.rds"))

tmp <- tempdir()
st_write(conc_prob_sf, file.path(tmp, "file.shp"), quiet=TRUE)
conc_prob_sf_shp <- st_read(file.path(tmp, "file.shp"), quiet=TRUE)

st_write(conc_prob_sf, file.path(tmp, "file.geojson"), quiet=TRUE)
conc_prob_sf_geoj <- st_read(file.path(tmp, "file.geojson"), quiet=TRUE)

st_write(conc_prob_sf, file.path(tmp, "file.kml"), quiet=TRUE)
conc_prob_sf_kml <- st_read(file.path(tmp, "file.kml"), quiet=TRUE)

dat_all <- list(conc_prob_sf=conc_prob_sf, 
                conc_prob_sf_shp=conc_prob_sf_shp,
                conc_prob_sf_geoj=conc_prob_sf_geoj,
                conc_prob_sf_kml=conc_prob_sf_kml)

sapply(dat_all, st_area)
#>      conc_prob_sf  conc_prob_sf_shp conc_prob_sf_geoj  conc_prob_sf_kml 
#>          16251347          16251347          16251347          16251347
sapply(dat_all, \(x) expanse(vect(x)))
#>      conc_prob_sf  conc_prob_sf_shp conc_prob_sf_geoj  conc_prob_sf_kml 
#>           1211584          16181959           1211584           1211584
sapply(dat_all, \(x) expanse(vect(x), transform=FALSE))
#>      conc_prob_sf  conc_prob_sf_shp conc_prob_sf_geoj  conc_prob_sf_kml 
#>           1211584          16181959           1211584           1211584

## plot(conc_prob_sf)
## plot(vect(conc_prob_sf))
## plot(vect(conc_prob_sf_shp))
```

<sup>Created on 2024-12-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

[poly_weird.zip](https://github.com/user-attachments/files/18053467/poly_weird.zip)

**Comment by rhijmans** [comment]
Your polygon is indeed weird. There is one big polygon "ring" with 11 holes and a few very small polygons (rings) that are mostly irrelevant for the discussion here. The big polygon is not valid because the 11 holes are outside the main polygon "ring"; so they cannot be valid holes. This can be "fixed" with `terra::makeValid` or `fillHoles` depending on what they should represent (who knows?). When writing the shapefile this is partly corrected for by making the holes that are outside the bounding box of the main ring parts, new rings of the multipolygon; but two small "holes" that are entirely inside this bounding box remain as "holes" ever though this is invalid.

Furthermore, sf using "s2" to compute area and that further complicates the comparison with terra.

```
library(sf)
#Linking to GEOS 3.12.2, GDAL 3.9.3, PROJ 9.4.1; sf_use_s2() is TRUE
library(terra)
#terra 1.8.3
sf <- readRDS("poly_weird.rds")

# two answers with sf 
sf_use_s2(TRUE)
st_area(sf)
#16251347 [m^2]
sf_use_s2(FALSE)
#Spherical geometry (s2) switched off
st_area(sf)
#-1211584 [m^2]
``` 

With terra 

```
te <- vect(sf)
expanse(te)
#[1] 1211584
is.valid(te)
#[1] FALSE
vte <- makeValid(te)
expanse(vte)
#[1] 16181959
``` 

To unpack these differences:

```
nothole <- fillHoles(te, FALSE)
holes <- fillHoles(te, TRUE)
expanse(nothole) - sum(expanse(holes))
#[1] -1211584
expanse(nothole) + sum(expanse(holes))
#[1] 16187294

xnothole <- erase(nothole, holes)
xholes <- erase(holes, nothole)
x <- aggregate(rbind(xnothole, xholes))
expanse(x)
#[1] 16182165
```

That last one is very close to the result from `makeValid` (which I would pick as the best answer if you want non-overlapping holes to counted as additional area).  

Some illustration 

```
plot(vte)
lines(fillHoles(te, T), col="blue", lwd=2) # "holes in original data
lines(fillHoles(vte, T), col="red", lwd=3) # actual holes
``` 

Also, writing to shapefile is interesting. It makes new rings from the holes that are entirely outside the extent of the main ring, but keeps as (invalid) holes two small "islands" to the south-east of the main ring inside the extent of the main ring. That makes the shapefile result a bit smaller:

```
writeVector(te, file.path(tempdir(), "te.shp"), overwrite=TRUE)
te2 <- vect(file.path(tempdir(), "te.shp"))
#[1] 16124530
```

I am not sure about what to do in these situations. For example, should all polygons be tested for validity before processing? Should warnings be given, errors be triggered?

**Comment by MatthieuStigler** [comment]
Hi Rob

Thanks a lot for this forensic work! Sorry to make you go through this, I missed the validity part, I had checked with `st_is_valid` but not with `is.valid`. I realize I could also have done `sf_use_s2(FALSE)` and `st_is_valid(conc_prob_sf)` to obtain `FALSE`.

And yes, I'm not sure either what to think about that. I guess the answer is it depends on how fast `is.valid()` is? Or eventually add it as an argument to `expanse()` check.is.valid=TRUE or FALSE by default?

And yes, good question, where this polygon come from......

Thanks again!

**Comment by rhijmans** [comment]
I have added a waring about this to the manual. I will leave it at that for now, under the assumption that this is a very rare case.
