### ISSUE TITLE
predict to 'large' raster 

### ISSUE THREAD

**Issue by salder** [rspatial/terra#173]
Hi, 
the terra package is really a very nice improvement compared to the raster. Thank you for the work!
 Nevertheless, I come to the same problems when trying to do some predictions on larger raster files (like the whole mountain range in Skaninavia). In the raster packages I used a work around defining a function as described in some very useful instructions (pdf file) using blocksize() and a loop
like
bs <- blockSize(out,minblocks = 2000)
 out <- writeStart(out, 'test.grd', overwrite=TRUE)
 for (i in 1:bs$n) {
   b1<- getValues(b1.c, row=bs$row[i], nrows=bs$nrows[i] )
   b2<- getValues(b2.c, row=bs$row[i], nrows=bs$nrows[i] )
   wetness<- getValues(wetness.c, row=bs$row[i], nrows=bs$nrows[i] )
  df.temp<-data.frame(b1,b2,wetness)
   pre<-predict(fit.gam,df.temp,type="response")
   out <- writeValues(out, pre, bs$row[i])
}

So I thought that I do not need this work around any longer, but running the terra::predict 
I get again memory problems. Hm, do I have to go back to the loop solution ore is there an other possibility to come over this in terra? 
(A little bit stange is that the prediction function works on small (ok 17 GB) sometimes well, but sometimes not? Even efter setting terraOptions(memfrac=0.8, tempdir = "C:/TEMP"), I have got this strange result?

Thank yo for your help
Best regards
Sven Adler

...

**Comment by rhijmans** [comment]
This is probably due to this (solved) issue https://github.com/rspatial/terra/issues/163 in the development version (not on CRAN yet). Are you using the CRAN version?   I have also made the default assumptions  about memory requirements a bit more stringent in response to this one: https://github.com/rspatial/terra/issues/165 .  It is a trade-off between performance and speed, and somewhat platform dependent; but the defaults should never lead to a crash. 

It would be helpful to have more info, such as `show(predictors)` and `sessionInfo()`. You can also gain some understanding from `terra:::mem_info(predictors)` and `predict(predictors, m, verbose=TRUE)` (the latter in command line so that if your session crashes you still have the output).

`memfrac=0.8` is really high, if you want to be safe, then perhaps use `memfrac=0.4` .

**Comment by salder** [comment]
Hi Robert, 
thank you for your very fast answer! You are right, I was working with the CRAN version. I'm now insalling the dev version and try it out.

**Comment by salder** [comment]
It works for the "samll" without problem, thanks again!
