### ISSUE TITLE
focal function crashes R when setting circular window to 1000 meters

### ISSUE THREAD

**Issue by fRIdanwismer** [rspatial/terra#182]
This keeps crashing my R session:
```
library(terra)
# rasters are in nad83 utm11n
rd30m <- terra::rast("X:/rd30m.tif")
rd1km <- terra::focal(rd30m,focalMat(rd30m,1000,"circle"))
```

**Comment by rhijmans** [comment]
Can you `show(rdm30)` Is this with the CRAN version? I am asking because I may have fixed this yesterday with the development version. It would be great if you could try with that version if you can (I plan to send it CRAN over the weekend).

**Comment by fRIdanwismer** [comment]
This is interesting, the rd30m.tif is binary with 0 and 1 cells.  It seems that this is being lost when I read in the raster...
```
rd30m <- terra::rast("X:/rd30m.tif")
rd30m

class       : SpatRaster 
dimensions  : 4490, 4535, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 301762.3, 437812.3, 5876699, 6011399  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=11 +datum=NAD83 +units=m +no_defs 
source      : rd30m.tif 
name        : rd30m 
min value   :     0 
max value   :     0 

rd30m <- raster("X:/rd30m.tif")
rd30m
class      : RasterLayer 
dimensions : 4490, 4535, 20362150  (nrow, ncol, ncell)
resolution : 30, 30  (x, y)
extent     : 301762.3, 437812.3, 5876699, 6011399  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=11 +datum=NAD83 +units=m +no_defs 
source     : X:/caribou/Development/CWTv2/tmpIP/20210325132130/rd30m.tif 
names      : rd30m 
values     : 0, 1  (min, max)
attributes :
 ID category
  0        0
'''

Also `show(rd30m)` seems to work
```
rd30m <- terra::rast("X:/rd30m.tif")
show(rd30m)
class       : SpatRaster 
dimensions  : 4490, 4535, 1  (nrow, ncol, nlyr)
resolution  : 30, 30  (x, y)
extent      : 301762.3, 437812.3, 5876699, 6011399  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=utm +zone=11 +datum=NAD83 +units=m +no_defs 
source      : rd30m.tif 
name        : rd30m 
min value   :     0 
max value   :     0 

```

**Comment by rhijmans** [comment]
The 0/1 being lost seems to be because the file has an attribute table (such a table can be used to set labels to codes (factors in R speak), e.g. "0 = water" and "1 = forest"). `terra` uses these tables more than `raster`. I think this is a good thing, but in this case, the table seems to only classify  0 as 0, and no value for 1. That won't affect things like aggregate or focal, but it might go wrong with `extract` (which would want to give you the factor, rather than the code) --- I need to try that. I will look at the issue with focal next.

**Comment by fRIdanwismer** [comment]
Thanks for that feedback, I will stay tuned about focal crashing. Let me know if you need me to test something.

**Comment by rhijmans** [comment]
This works for me with the development version; I am pretty sure that this is because of the [changes I made](https://github.com/rspatial/terra/issues/88#issuecomment-806354057) yesterday (!). The error was to not account for the the size of the window in the memory requirements (67 * 67 in your case, so that is a lot. I also realized that they way I implemented `focal` is not efficient for large windows, and I hope to also improve that before sending a new version to CRAN.
