### ISSUE TITLE
Confusing installation error.

### ISSUE THREAD

**Issue by bholtdwyer** [rspatial/terra#198]
I'm trying to install on MacOs Catalina, 10.15.7. When I do the usual `install.packages("terra")`, it asks whether I want to install a more recent version (1.17 vs 1.14) that needs compilation. When I say "yes", I get the following output over and over in my R terminal:

`1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/usr/local/Cellar/proj/7.2.1/include -DHAVE_PROJ_H -I/usr/local/Cellar/gdal/3.2.2/include -I/usr/local/Cellar/geos/3.9.1/include -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
In file included from RcppFunctions.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp.h:57:
/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
`

It then eventually (after repeating this several times) ends with

`make: *** [RcppModule.o] Interrupt: 2
ERROR: compilation failed for package ‘terra’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/terra’`

I've installed the most recent version of the Rcpp package.

I have no idea what this means or what to do about it.

**Comment by rhijmans** [comment]
My guess is that that warning about Rcpp is not related for the installing failing. It is a Rcpp issue that [has been fixed](https://stackoverflow.com/a/65993877/635245) but is not on CRAN yet.

Unfortunately the CRAN build failed for OSX / current R. I have written them about it, but not heard back yet.  

I can install on mac in a homebrew installed version of R (after also installing GDAL see instructions at the bottom of the main github page for this repo) --- but not with the CRAN/binary version of R; presumably because it cannot find GDAL.

**Comment by rhijmans** [comment]
A new version is now on CRAN and should become available for OSX in a couple of days
