### ISSUE TITLE
Some functions in the documentation are not available in the terra package

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#244]
Some functions in the documentation are not available in the terra package - https://rspatial.github.io/terra/reference/terra-package.html:

The ones I found missing are `cellSize()` and `expanse()`.

**Comment by rhijmans** [comment]
`expanse` does not work, it seems, because it is documented in a file called `area.Rd` and packagedown somehow creates the wrong link. Not sure why, as it can handle this situation in other cases (e.g. it creates the correct link for `delauny` to go to `voronoi.html`.  I have renamed `area.Rd` to `expanse.Rd`. `cellSize` works for me.

**Comment by Nowosad** [comment]
Thanks! I cannot access the `cellSize()` and `expanse()` functions in the CRAN version of the package. Now, I installed the development version and everything works fine. Thanks for improving the documentation!

**Comment by kadyb** [comment]
I also noticed this problem with linking documentation in`pkgdown` - many functions don't redirect correctly (https://github.com/rspatial/terra/pull/205). I don't know why there is such a problem, but maybe we should write to the package developers?
