### ISSUE TITLE
Functions to check if the SpatRaster is in memory or not

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#321]
Checking if the data was in memory or not was possible in **raster** with `inMemory()` and `fromDisk()`. I have searched for similar functions in **terra**, but have not found any. Is it possible to check if the data is in memory in **terra**?

``` r
library(raster)
#> Loading required package: sp
rs = raster(system.file("external/test.grd", package = "raster"))
inMemory(rs)
#> [1] FALSE
fromDisk(rs)
#> [1] TRUE

library(terra)
#> terra version 1.4.1
rs2 = rast(system.file("external/test.grd", package = "raster"))
inMemory(rs2)
#> Error in inMemory(rs2): no slot of name "data" for this object of class "SpatRaster"
fromDisk(rs2)
#> Error in fromDisk(rs2): no slot of name "data" for this object of class "SpatRaster"
```

<sup>Created on 2021-09-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
In the CRAN version you can use `sources` but then you need to do some additional manipulation 

```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
sources(s)
#                                       source nlyr
#1 C:/soft/R/R-4.1.1/library/terra/ex/logo.tif    3

x <- c(s, s*1)
sources(x)
#                                       source nlyr
#1 C:/soft/R/R-4.1.1/library/terra/ex/logo.tif    3
#2                                                3
``` 

I have now added `inMemory` to `terra` (it was there, but not exported). Please note that it reports by *data source*, not by *layer*
 
```
nlyr(s)
#[1] 3
inMemory(s)
#[1] FALSE
 
inMemory(x)
#[1] FALSE  TRUE
``` 

Unless you do

```
inMemory(x, bylayer=TRUE)
# [1] FALSE FALSE FALSE  TRUE  TRUE  TRUE
``` 

A difference with `raster` is that in `terra`, `inMemory` is `TRUE` for a raster with no associated cell values. 

```
inMemory(rast())
[1] TRUE
raster::inMemory(raster::raster())
[1] FALSE
``` 

There is a name clash with CRAN raster that has been fixed in development raster.
