### ISSUE TITLE
'lines' SpatVector can't be converted to "Spatial"

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#331]
Dear colleagues,
I'm having no problems converting SpatVector points or polygons to "Spatial" class (or plotting them with 'spplot') whenever necessary (e.g. for using functions that don't support 'SpatVector' class objects), but for **lines** this produces an error:
```
lon <- c(-116.8, -114.2, -112.9, -111.9, -114.2, -115.4, -117.7)
lat <- c(41.3, 42.9, 42.4, 39.8, 37.6, 38.3, 37.6)
lonlat <- cbind(lon, lat)

pts <- vect(lonlat)
spplot(pts)
as(pts, "Spatial")  # no problem

pols <- vect(lonlat, type = "polygons")
spplot(pols)
as(pols, "Spatial")  # no problem

lns <- vect(lonlat, type = "lines")
spplot(lns)
as(lns, "Spatial")
# unlike with points and polygons, the last two commands produce Error in .local(obj, ...) : cannot derive coordinates from non-numeric matrix
```
I'm using the latest CRAN version of 'terra', and I tried this on both Linux and Windows. I also tried with the 'terra' development version installed with `repos='https://rspatial.r-universe.dev'`. A fix would be greatly appreciated. Cheers!

**Comment by rhijmans** [comment]
Thank you very much for reporting this bug. It was fixed with https://github.com/rspatial/raster/commit/d879e67aecbce8a3ad53310abb1aa915151dc581
To see it you need to install the development version of `raster` , you can do that (within an hour or so) with 
`install.packages('raster', repos='https://rspatial.r-universe.dev')`
