### ISSUE TITLE
Subtracting two multi-layer SpatRasters produces result with invalid varnames

### ISSUE THREAD

**Issue by dbaston** [rspatial/terra#342]
In this example, I would expect `length(varnames(x)) == length(nlyr(x))`, but it is not. This prevents the use of code like `names(x) <- paste('val_', varnames(x), sep='')`

```
a <- c(rast(matrix(runif(100), nrow=10)),
       rast(matrix(runif(100), nrow=10)))
varnames(a) <- 'a'

b <- c(rast(matrix(runif(100), nrow=10)),
       rast(matrix(runif(100), nrow=10)))
varnames(b) <- 'b'

x <- b - a
length(varnames(x))
```

**Comment by rhijmans** [comment]
`names` are a property of "layers", but `varnames` are a property of "data sources". I added them to represent the names of sub-datasets as are found in NetCDF and HDF files. 

 `a` and `b` have two sources (both in memory); but after the computation they are reduced to one (in-memory) source. 

```
sources(a)
#  source nlyr
#1           1
#2           1

sources(x)
#  source nlyr
#1           2
```

The `varname` concept is not much developed. Perhaps because sources are generally not that relevant to users. Perhaps there are other things to consider that I have not considered.
