### ISSUE TITLE
naming consistency

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#357]
I just have noticed that the previous `disaggregate` is now called `disagg`. Do you also plan to change `aggregate` to `agg`? These two functions are kind of two sides of a coin...

[This is a minor pet peeve of mine - feel free to just ignore and close this issue anytime]

**Comment by rhijmans** [comment]
I do not like it either. But I cannot use disaggregate and have `raster` depend on `terra`, because `sp` also exports disaggregate.  I am not sure if it is better to have two bad names that are consistent or one bad name that is inconsistent. Or a fair name, but that is not related to aggregate such as "divide", or an inconsistent use of capitalization "disAggregate"

**Comment by erydit** [comment]
Maybe a naming approach that is becoming more and more popular is better alternative to sudden renames and breaks of version compatibility?
Just add prefix ter_ to all public terra functions? 

For example, packages that use prefixes: sgringr, forcats, furrr, googleAuthR.
