### ISSUE TITLE
Performance of assigning new values

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#358]
The performance of assigning new values with `terra::values()<-` is visibly slower than with `raster::values()<-`. It can be seen below with terra's function slower ~10 times for a small raster, and ~5 times for a larger one. Is there a way to improve the `terra::values()<-` speed?

``` r
library(raster)
#> Loading required package: sp
library(terra)
#> terra version 1.4.8
r_set_vals <-  function(r, vals){
  raster::values(r) <- vals
  r
}

t_set_vals <-  function(t, vals){
  terra::values(t) <- vals
  t
}

# smaller rasters
r <- raster(ncol = 10, nrow = 10)
t <- rast(ncol = 10, nrow = 10)

vals <- 1:ncell(r)

bench::mark(
  r_set_vals(r, vals),
  t_set_vals(t, vals),
  check = FALSE,
  iterations = 1000
)
#> # A tibble: 2 x 6
#>   expression               min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>          <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 r_set_vals(r, vals) 159.02µs  174.3µs     4244.        0B    12.8 
#> 2 t_set_vals(t, vals)   1.91ms    2.5ms      314.    53.2KB     7.07

# larger rasters
r2 <- raster(ncol = 1000, nrow = 1000)
t2 <- rast(ncol = 1000, nrow = 1000)

vals2 <- 1:ncell(r2)

bench::mark(
  r_set_vals(r2, vals2),
  t_set_vals(t2, vals2),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 x 6
#>   expression                 min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>            <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 r_set_vals(r2, vals2)   3.09ms   3.46ms     280.         0B     0   
#> 2 t_set_vals(t2, vals2)  13.04ms  15.64ms      61.8    7.63MB     9.24
```

<sup>Created on 2021-10-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
I have looked at this intensively, and that has helped speed up some things. But let's first consider your example 

```
library(raster)
library(terra)
r_set_vals <-  function(r, vals){  raster::values(r) <- vals } 
t_set_vals <-  function(t, vals){  terra::values(t) <- vals }
r2 <- raster(ncol = 10000, nrow = 10000)
t2 <- rast(r2)
vals <- 1:ncell(r2)

bm <- bench::mark(
    r_set_vals(r2, vals),
    t_set_vals(t2, vals),
    check = FALSE,
    terations = 10
)
bm[,1:5]
## A tibble: 3 x 5
#  expression                min   median    `itr/sec` mem_alloc
#  <bch:expr>           <bch:tm> <bch:tm>        <dbl> <bch:byt>
#1 r_set_vals(r2, vals)    173ms    176ms         5.67    1.68KB
#2 t_set_vals(t2, vals)    703ms    703ms         1.42  762.94MB
#3 terations                   0      1ns 303388849.          0B
``` 

This still does not look good.  However, we need to consider that R does not actually create a vector when you do `1:ncell(x)`  (it only promises to compute it when needed). And that is why:

```
system.time(vals <- 1:ncell(r2))
#   user  system elapsed 
#      0       0       0 
```

To get a more general comparison, we can force the vector to be created, as in most cases you would have a vector of values, not a promise

```
vals <- 1 * (1:ncell(r2))
bm <- bench::mark(
    r_set_vals(r2, vals),
    t_set_vals(t2, vals),
    check = FALSE,
    iterations = 10
)
bm[,1:5]
## A tibble: 2 x 5
#  expression                min   median `itr/sec` mem_alloc
#  <bch:expr>           <bch:tm> <bch:tm>     <dbl> <bch:byt>
#1 r_set_vals(r2, vals)    361ms    369ms      2.69        0B
#2 t_set_vals(t2, vals)    465ms    476ms      2.04    3.25KB
```

I am happy with this result. Even though `raster` is faster here. The underlying issue is that raster can directly use `vals` whereas terra must make a copy to create a `std::vector<double>`  --- although there could be a lot more to it that I do not fully comprehend that affect raster (smart R stuff that I do not control) 

One thing that is clear is that it is relatively expensive to use `v <- values(x)`, do something with `v` and then do `values(x) <- v`. That will inevitable in some cases, but in other cases it may be avoided by changing the values of `x` in-place. I have done that for the replacement functions such as `x[1:5]<- 10`. 

With CRAN-terra I get
```
x <- setValues(t2, 1:ncell(t2)) 
system.time(x[1:5] <- 55)
#   user  system elapsed 
#   1.06    0.58    1.64 
```

But with development-terra I get

```
x <- setValues(t2, 1:ncell(t2)) 
system.time(x[1:5] <- 55)
#   user  system elapsed 
#      0       0       0 
```

Perhaps there are other places where that approach can be used.

**Comment by rhijmans** [comment]
if you actually *wanted* the values to be `1:ncell(x)` it is now faster to use `init` (it was not before). 

```
system.time(x <- setValues(t2, 1:ncell(t2)))
#   user  system elapsed 
#   0.63    0.21    0.85 
 
system.time(x <- init(t2, "cell"))
#   user  system elapsed 
#   0.45    0.08    0.53 
```

**Comment by Nowosad** [comment]
Thanks, @rhijmans
