### ISSUE TITLE
Speed and Ram usage of coverting lat-lon to Vect

### ISSUE THREAD

**Issue by BastienFR** [rspatial/terra#413]
I have a enormous table of lat-lon (220 millions observations).  I want to convert them into a spatial object (point shape) and rasterize them.  I do that in terra and it works.  However, it is slow and uses lots of RAM.  The `rasterize` part of my code works perfectly. It is speedy and doesn't use much Ram, however the creation of the `vect` object is the most problematic one.  I did the same thing with `sf` and it is faster and is less memory hungry.

This is not a question or a bug per se, I just observed a behaviour that I wanted to share here in case something can be done.

So in my real life work, converting my 220 millions observations table into a point shapefile take:

- sf: 274 sec - 45 GB
- terra: 478 sec - 195 GB

The difference (mostly in Ram), is kind of limiting.

Here is a reproducible example that shows the speed difference:

```
## run on a Ryzen 5 1600 with 16 GB of ram, not the same machine I use for work
library(sf)
library(terra)
library(tictoc)

nnn <- c(100000, 500000, 2500000, 1000000, 5000000, 7500000, 10000000)
for(nn in nnn){

  dd <- data.frame(id = 1:nn, lat= runif(nn, 45, 50), lon = runif(nn, -80, -60))
  
  tic(paste0("sf_", nn))
  dd.sf <- st_as_sf(dd, coords = c("lon", "lat")) %>% st_set_crs(4326)
  toc(log=T, quiet = T)
  
  tic(paste0("te_", nn))
  dd.terra <- vect(dd, geom = c("lon", "lat"), crs = "EPSG:4326")
  toc(log=T, quiet = T)

  gc()
}


library(dplyr)
library(ggplot2)
tic.log(format = F) %>%
  unlist %>% 
  matrix(length(nnn)*3,3,byrow = T) %>% 
  as.data.frame() %>% 
  mutate(time = as.numeric(V2)-as.numeric(V1),
         fun = substr(V3, 1, 2),
         nn = as.numeric(substr(V3, 4, 88))) %>% 
  ggplot(aes(x=nn, y=time, color=fun)) +
  geom_point()+
  geom_line()
```
with timing:
![image](https://user-images.githubusercontent.com/10979480/143065050-1d924974-5f9a-497b-b234-4dd211981016.png)

As stated above, it's not a bug or a complain.  Feel free to close this issue without any follow up.  However, if you feel that the `vect` function can be speed up and use less Ram, know that it will be useful.  Thanks.

**Comment by rhijmans** [comment]
Thank you for this. This happens because the data model for points is the same as for lines and polygons; I knew that was going to be inefficient, but simplicity has great benefits for the developer. It is time that I fix this, and I plan to do so sometime this year.

**Comment by mdsumner** [comment]
@rhijmans could you expand on this a little, you mean the data model that is in SpatLib?

just some quick description or pointers to tge code base would be of interest, if it's no bother

**Comment by rhijmans** [comment]
@mdsummer that tis indeed what I mean. The SpatVector is a std::vector of geometries. That is convenient for polygons, but overkill for points. For example, each geometry stores an extent, which is not relevant for a single point, but it needs to be set.  And this explains the larger RAM footprint as well. I want to redesign the class for efficiency and memory use (and I need a good chunk of dedicated time for that).  

There are of course other things. I have now rewritten a method to set point data, and it is now used at the R end (instead of a more general method). That helps quite a bit, see below comparing sf and two approaches with terra. The faster approach with terra uses a matrix such that attributes are not set. 

```

library(sf)
library(terra)
library(tictoc)

nnn <- c(100000, 500000, 2500000, 1000000, 5000000, 7500000, 10000000)
for(nn in nnn){
  dd <- data.frame(id = 1:nn, lat= runif(nn, 45, 50), lon = runif(nn, -80, -60))

  tic(paste0("sf_", nn))
  dd.sf <- st_as_sf(dd, coords = c("lon", "lat")) %>% st_set_crs(4326)
  toc(log=T, quiet = T)
 
   tic(paste0("td_", nn))
  dd.terra1 <- vect(dd, geom = c("lon", "lat"), crs = "EPSG:4326")
  toc(log=T, quiet = T)

  tic(paste0("tm_", nn))
  dd.terra2 <- vect(as.matrix(dd[, 3:2]), crs = "EPSG:4326")
  toc(log=T, quiet = T)
  gc()
}

library(ggplot2)
tic.log(format = F) %>%
  unlist %>% 
  matrix(length(nnn)*3, 3, byrow = T) %>% 
  as.data.frame() %>% 
  dplyr::mutate(time = as.numeric(V2)-as.numeric(V1),
         fun = substr(V3, 1, 2),
         nn = as.numeric(substr(V3, 4, 88))) %>% 
  ggplot(aes(x=nn, y=time, color=fun)) +
  geom_point()+
  geom_line()
  ```

![points](https://user-images.githubusercontent.com/11481397/145730070-59f5f1c5-5b75-4113-a079-5ed75d3116cf.png)

**Comment by rhijmans** [comment]
The data.frame method now has the same speed as the matrix method and they are about 3x as fast as sf (whereas the data.frame method was about 4x slower).

```

library(sf)
library(terra)
library(tictoc)
nnn <- c(100000, 500000, 2500000, 1000000, 5000000, 7500000, 10000000)
for(nn in nnn){
  dd <- data.frame(id = 1:nn, lat= runif(nn, 45, 50), lon = runif(nn, -80, -60))
  tic(paste0("sf_", nn))
  x <- st_as_sf(dd, coords = c("lon", "lat")) %>% st_set_crs(4326)
  toc(log=T, quiet = T);  rm(x); gc()
  tic(paste0("td_", nn))
  x <- vect(dd, geom = c("lon", "lat"), crs = "EPSG:4326")
  toc(log=T, quiet = T); rm(x); gc()
  tic(paste0("tm_", nn))
  x <- vect(as.matrix(dd[, 3:2]), crs = "EPSG:4326")
  toc(log=T, quiet = T); rm(x); gc()
}

library(ggplot2)
tic.log(format = F) %>% unlist %>% matrix(length(nnn)*3, 3, byrow = T) %>% as.data.frame() %>% 
  dplyr::mutate(time = as.numeric(V2)-as.numeric(V1), fun=substr(V3, 1, 2), nn=as.numeric(substr(V3, 4, 88))) %>% ggplot(aes(x=nn, y=time, color=fun)) + geom_point()+ geom_line()
```  

(note that the td (`terra-data.frame`) and tm (`terra-matrix`) lines are difficult to distinguish)  

![points2](https://user-images.githubusercontent.com/11481397/145731818-cc8eba30-3271-48c0-aa2f-1f81cea9f2eb.png)


The `data.frame` method is now faster because all data is passed to C++ once, instead of first for the geometry, and then for the attributes.  The `matrix` method gained a lot of speed by setting the crs *before* adding the geometry to the SpatVector. In R that is important because `crs(x) <- ""` returns a deep copy, to avoid confusion if prior to that `x <- y` was done (a shallow copy). But copying a big object takes time. The `data.frame` method sets the crs in-place, in C++, and that is even better.  So much for my intuition about speed bottlenecks? Maybe, but I think the SpatVector class redesign is still a good idea. For one to reduce the memory footprint, but surely also to improve speed further. And the R code should make changes in-place where that is safe.

**Comment by rhijmans** [comment]
@BastienFR :  I had overlooked *why* you were looking at the speed of `vect`: 

> I have a enormous table of lat-lon (220 millions observations). I want to (...) rasterize them. 

It should not be necessary to first create a `SpatVector` from coordinates only for the `rasterize` method to extract the coordinates again. You can now just use a matrix: 

```
library(terra)
r <- rast(xmin=0, ncols=18, nrows=18)
set.seed(1)
p <- spatSample(r, 1000, xy=TRUE, replace=TRUE)

x <- rasterize(p, r, fun=sum)
y <- rasterize(p, r, value=1:nrow(p), fun=max)
```

**Comment by rhijmans** [comment]
Closing this as I think the issues have been addressed. There is still the plan to rework the internal storage of points.
