### ISSUE TITLE
setValues crashing R

### ISSUE THREAD

**Issue by glorious1** [rspatial/terra#414]
When I attempt to use setValues on my rasters, R crashes.  The following example uses a raster of the same sort I am using.
```
library(terra)
A <- rast( nrow=2100, ncol=3480, xmin=-108.4, xmax=-105.5, ymin=38.7, ymax=40.45 )
values(A) <- round( runif( n=ncell(A), min=0, max=100 ) )

B <- setValues( x=A, values=0 )  # crash
```
By the way, this also crashes:
```
B <- A
values(B) <- 0
```
I've been able to get this to work, although sometimes it gives the following error while actually working:
```
> B <- A
> B[] <- 0
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
```
I was able to do these things using `raster` with rasters having twice as many cells.

**Comment by rhijmans** [comment]
Thank you very much, that is a really ugly bug. Should be fixed now. 

I assume you are on OSX because R crashed when I run your code. While I got this error on windows and ubuntu

`Error in y@ptr$setValues(values, opt) : std::bad_alloc` 

`values` calls `setValues` and if you provide a single value that call `init` (and that is where the bug was).
With your version, a work-around is  `B <- setValues( x=A, values=rep(0, size(A) )` 

These error *messages* (but not actual errors in the workflow): 
`Error in x$.self$finalize() : attempt to apply non-function` 
are a [big nuisance](https://github.com/rspatial/terra/issues/30) that I should to look into again.

**Comment by glorious1** [comment]
Yes, I'm on macOS Monterey, 12.0.1

Thank you for addressing this so quickly!
