### ISSUE TITLE
plotRGB error for rast with NA values

### ISSUE THREAD

**Issue by StephanLo** [rspatial/terra#433]
Hello, thanks for the cool package! 
I am using terra 1.3-22

After masking a rast object (thus introducing NA values) plotRGB gives the error: 
"Error in grDevices::rgb(RGB[, 1], RGB[, 2], RGB[, 3], alpha = alpha, maxColorValue = scale) : color intensity NA, not in 0:255" 

However, the plotRGB documentation says the function has an argument colNA   --> color for the background (NA values) 
which suggest that it should be possible to have NA values in the rast given to plotRGB. Am I misunderstanding this? 

Thank you!

Small example: 
```R
library(terra)
r <- rast(nrows = 2, ncols = 2, nlyr =3)
y <- runif(12)
y[2] <- NA

r <- setValues(r,y)
plot(r)
# plots 3 layers with 1 NA pixel in lyr.1

plotRGB(r)
# Error in grDevices::rgb(RGB[, 1], RGB[, 2], RGB[, 3], alpha = alpha, maxColorValue = scale) : 
# color intensity NA, not in 0:255
```

**Comment by rhijmans** [comment]
I do not see that error when I do `plotRGB(r, 1)`; but since the values are between 0 and 1 in this case, the plot looks better when you do `plotRGB(r, scale=1)`. 

You are using an ancient version. Please use at least the current version from CRAN, but you can also use the development version (see instructions [here](https://github.com/rspatial/terra)).

**Comment by StephanLo** [comment]
Updating fixed it. I should have done that first.

Thank you for the fast response
