### ISSUE TITLE
` as.polygons()` does not work after `extend()`

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#450]
``` r
library(spData)
library(terra)
#> terra version 1.5.4

elev = rast(system.file("raster/elev.tif", package = "spData"))
elev_2 = extend(elev, c(1, 2))

as.polygons(elev_2, dissolve = FALSE)
#>  class       : SpatVector 
#>  geometry    : none 
#>  dimensions  : 0, 1  (geometries, attributes)
#>  extent      : 0, 0, 0, 0  (xmin, xmax, ymin, ymax)
#>  coord. ref. : lon/lat WGS 84 (EPSG:4326)
```

<sup>Created on 2021-12-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
Thanks -- I am sorry for creating these errors, but it is very useful for me. The problem was really with `extend` and due some of the optimizations for speed that I have been working on. I did some more overhaul to avoid this type of error in the future. I now get: 

```
p = as.polygons(elev_2, dissolve = FALSE)
plot(p, "elev")
``` 
![elev](https://user-images.githubusercontent.com/11481397/146653673-2641b2b8-4a35-42a9-9b01-9d396dd85340.png)

**Comment by Nowosad** [comment]
Thanks!
