### ISSUE TITLE
memfrac lower than 0.1

### ISSUE THREAD

**Issue by mstrimas** [rspatial/terra#476]
I'm running some `terra` code on a cluster with slurm where each node has 256 GB RAM and 64 cores. For a given job, the amount of RAM allocated is proportional to the number of cores (e.g. 4 GB for 2 cores), however, `terra` seems to think it has access to all 256 GB, and I'm consistently having my jobs killed because they're using too much RAM. I tried using `terraOptions(memfrac = 0.015)` (4/256 = 0.015), however, this silently uses 0.1 instead, which is the lower threshold specified in the `terraOptions()` documentation. Is there a way to use a lower `memfrac` or another way to control memory usage of `terra`.

**Comment by rhijmans** [comment]
Thanks for reporting this. I ran into the very same issue myself a whole ago, and worked around it; but never fixed it. 

I now changed terra so that you can set memfrac to 0. terra will still use some memory, of course. In most cases the very minimum is one row of raster values (and perhaps a copy or two of these values).  This will go to CRAN very soon, but it may take a while to hit your cluster.  I need to do some testing, as this may fail for some function that need multiple rows, such as focal; but that can be fixed. 

With older versions, a work-around is to use argument  `steps` that you can provide as additional argument, or as an element of `wopts` if the additional argument are used for something else.  The extreme case would be `steps=nrow(x)` (where `x` is the input SpatRaster, but you could do `steps=nrow(x)/10` . 

I opted for processing by tiles, which can be nice if you have relatively few, but very large files. It is a bit more involved, and on my to-do list to generalize that and make it available to all functions, as an option so that you could specify the number of tiles, and the tile number so that you can parallelize. Tiles go to a folder with a .vrt file that virtually combines them. The benefit was that if a job got killed none of the tiles already done were lost.
  
One reason why I did not fix this earlier that I was wondering if there would be a generic way to discover the number of cores that share the available RAM so that the memory available can be automatically adjusted; but may be rather complicated or system specific like calling slurm commands.  

However, another possibility would be to allow setting the available RAM as an option. I think I will add that.

**Comment by mstrimas** [comment]
This should be perfect! Also, I was aware of the `steps` argument, that should come in handy, thanks!

**Comment by rhijmans** [comment]
terra now has a new option `maxmem` that allows you to cap the amount of RAM (expressed in GB) that is deemed available.

```
library(terra)
#terra 1.5.9
r <- rast(res=1/1200)
mem_info(r)

#------------------------
#Memory (GB) 
#------------------------
#available       : 10  (maxmem)
#allowed (60%)   : 6
#needed (n=1)    : 695.23
#------------------------
#proc in memory  : FALSE
#nr chunks       : 194
#------------------------

## Cap available RAM

terraOptions(memmax=10)
terraOptions()
#memfrac   : 0.6
#tempdir   : C:/temp/RtmpMVMgRQ
#datatype  : FLT4S
#progress  : 3
#todisk    : FALSE
#verbose   : FALSE
#tolerance : 0.1
#memmax    : 10

mem_info(r)

#------------------------
#Memory (GB) 
#------------------------
#available       : 10  (maxmem)
#allowed (60%)   : 6
#needed (n=1)    : 695.23
#------------------------
#proc in memory  : FALSE
#nr chunks       : 194
#------------------------

## Reset with NA or number below zero

terraOptions(memmax=NA)
mem_info(r)

#------------------------
#Memory (GB) 
#------------------------
#available       : 50.77
#allowed (60%)   : 30.46
#needed (n=1)    : 695.23
#------------------------
#proc in memory  : FALSE
#nr chunks       : 39
#------------------------
```

**Comment by mstrimas** [comment]
Thanks! This is a huge help to be able to control memory usage either by the fraction of the total or the absolute amount of RAM.

**Comment by tylerhoecker** [comment]
I am struggling to control memory usage while using `tapp`. I specify `memfrac = 0`, `memmax = 5` and provide a temporary filename to the function being applied within `tapp`, but >50 GB of RAM is still being used. Yes, these are large files on the order of 10 GB each. 

I would expect `tapp` to respect the `memfrac` and `memmax` parameters. Is this not the case? 

I can work on generating a reprex if the issue is not clear. Thanks in advance!
