### ISSUE TITLE
Patches() misbehaving

### ISSUE THREAD

**Issue by dncarpenter** [rspatial/terra#478]
Hi I've been trying to use `patches()` and have been getting some errant behavior e.g. 
```
library(terra)  ## terra version 1.4.22
r <- rast(nrows=5, ncols=10)
set.seed(0)
values(r)<- round(runif(ncell(r))*0.7)
rp <- patches(r, directions=8, zeroAsNA=T) 
plot(rp)
freq(rp)
```
![image](https://user-images.githubusercontent.com/14809525/148796894-5f363e03-b87c-4ba8-8b8a-f9598d13c8e9.png)
`patches()` appears to be finding 8 different patches, where it should be finding just 5. Compare to `raster::clump()`:
```
r2 <- raster::raster(r)
r2c <- raster::clump(r2, directions=8)
freq(r2c)
plot(r2c)
```
![image](https://user-images.githubusercontent.com/14809525/148798883-c71be4e4-3a6c-4fc5-b3f6-369c4870c6fb.png)
Finds 5 (non-NA) patches (or clumps). In this example the rook's case (`directions=4`) appears to work the same for both `patches()` and ` clump()` however when working with much larger SpatRasters I have observed similar errant subdividing of patches with `directions=4`

**Comment by rhijmans** [comment]
This was mostly already fixed in the development version (in several steps, this was the last one: https://github.com/rspatial/terra/issues/466). Your example revealed one more bug (only showing itself if the last cells of the last row has a value), and that is now fixed too; just in time before sending this version to CRAN. 

I now see:

```
library(terra) 
#terra 1.5.10

r <- rast(nrows=5, ncols=10)
set.seed(0)
values(r)<- round(runif(ncell(r))*0.7)

rp <- patches(r, directions=8, zeroAsNA=T) 
plot(rp); text(rp)
```

![patches1](https://user-images.githubusercontent.com/11481397/148819343-621d0482-25d0-41e1-a4e6-4ed35f8e0b3e.png)


And for the same data, but no longer "global", thus the left and right-most columns are not connected.

```
xmin(r) <- 0
rp <- patches(r, directions=8, zeroAsNA=T) 
plot(rp, type="classes"); text(rp)
```
![patches2](https://user-images.githubusercontent.com/11481397/148819364-e37a2cf6-eb63-4c2c-9698-9249bd982fbf.png)

This example also shows that there can be gaps between patch IDs. That is not a bug, but I intend to change that as it can easily lead to confusion.

**Comment by rhijmans** [comment]
Gaps in the patch IDs can now be removed by setting the new argument `allowGaps` to `FALSE`.

```
rp <- patches(r, directions=8, zeroAsNA=TRUE, allowGaps=FALSE) 
plot(rp, type="classes"); text(rp)
```

![patches3](https://user-images.githubusercontent.com/11481397/148824056-527fb36c-a387-4369-879e-22b98bde5b04.png)
