### ISSUE TITLE
Using GPKG for rasters

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#499]
I tried to test if the GPKG format could be used for saving rasters. In principle it had worked on my example, but the resulting file has one more layer. Is this a **terra** or **GDAL** issue/feature?

``` r
library(terra)
#> terra 1.5.13
ter = rast(system.file("ex/logo.tif", package = "terra"))   
writeRaster(ter, "my_file.gpkg")
ter2 = rast("my_file.gpkg")
plot(ter2)
```

![](https://i.imgur.com/GY9Imv0.png)

<sup>Created on 2022-01-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rhijmans** [comment]
I thin that is the transparency (alpha) layer. I believe it is a feature of GPKG-raster when you appears to be designed for storing "images" (tiles) used web-mapping. But I need to check again. It is even weirder when you do 

```
library(terra)
ter = rast(system.file("ex/logo.tif", package = "terra")) 
RGB(ter) = NULL  
writeRaster(ter[[1]], "my_file.gpkg", datatype="INT1U", overwrite=T)
ter2 = rast("my_file.gpkg")
plot(ter2)
```

It repeats the single layer three times.

**Comment by rhijmans** [comment]
GPGK is not a general format suitable for raster data. It is a highly specialized file format for georeferenced pictures that can be used in mapping.  See [here](Have a look at this: https://gdal.org/drivers/raster/gpkg.html)

It is even unclear whether the fourth band you see is actually in the file because of a GDAL feature:

> By default, the driver will expose a GeoPackage dataset as a four band (Red,Green, Blue,Alpha) dataset

And you could do 

`r <- rast("my_file.gpkg", opt="BAND_COUNT=3")`

to ignore it.

But unless you are making tiles for (web-) mapping, GPGK is not suitable for raster data. That is too bad given the convergence to use it for vector data. Perhaps some day it will support raster data as well.

**Comment by Nowosad** [comment]
Thanks, Robert. That confirms my understanding (and hopes) as well.
