### ISSUE TITLE
Lost precision when resolving a scale factor for an integer variable

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#509]
Using [this HDF4 file](https://e4ftl01.cr.usgs.gov/DP131/MOLT/MOD21A1D.061/2003.01.01/MOD21A1D.A2003001.h12v04.061.2020084062741.hdf), renamed to "example.hdf":

```
> min(na.rm = T, raster::getValues(raster::raster('HDF4_EOS:EOS_GRID:"example.hdf":MODIS_Grid_Daily_1km_LST21:LST_1KM')))
[ snipped CRS warnings ]
[1] 241.86
> min(na.rm = T, as.data.frame(terra::rast("example.hdf"))$LST)
[1] 241
```

The relevant metadata from `gdalinfo example.hdf -sd 1` is

```
Band 1 Block=1200x833 Type=UInt16, ColorInterp=Gray
  Description = Daily 1km Land-surface Temperature
  NoData Value=0
  Unit Type: K
  Offset: 0,   Scale:0.02
```

I'm running `terra` c35f4d99df75025704e5f8e3ba1f6c78c67fbbeb on R 4.0.4.

**Comment by rhijmans** [comment]
Thanks, good catch. Since the last release, terra returns integers (instead of doubles) if that is what is stored in the file. I overlooked this situation where the file has integers, but the scale/offset create decimal numbers. Fixed with  https://github.com/rspatial/terra/commit/15a7a4d965ec63b77c5ae52e13f8f931c5ec2df8

I now get:

```
library(terra)
r  <- rast("MOD21A1D.A2003001.h12v04.061.2020084062741.hdf")
as.data.frame(r)$LST |> range()
#[1] 241.86 278.28
```

**Comment by Kodiologist** [comment]
I tip my hat to you, O fastest maintainer in the West.
