### ISSUE TITLE
as.spatvector function not available, neither from CRAN or compiling from source

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#536]
I'd like to use the function as.spatvector. However, it does not seem to be included with the terra package when I download from CRAN or when I use remotes to compile from source. I see reference to it in [terra](https://github.com/cran/terra)/man/), so why would I not have this function when the package is loaded?

**Comment by Rapsodia86** [comment]
Here is a description of the function: 
https://rdrr.io/cran/terra/man/as.spatvector.html
You use it by specifically defining the vector type: as.polygons(),  as.lines(), or as.points()

**Comment by rhijmans** [comment]
There is no function `as.spatvector` because it would be ambiguous. There is a helpfile with that name that @Rapsodia86 pointed to.  @Canderson156 you are not saying what you want to achieve, so perhaps none of this applies. If you want to coerce a sf or sp object, you can use `vect(x)` or `as(x, "SpatVector") instead.
