### ISSUE TITLE
global sum gives NA for all NA raster but cellStats and sum give 0

### ISSUE THREAD

**Issue by see24** [rspatial/terra#591]
`global(r, sum, na.rm = TRUE)` returns NA which is unexpected since `sum` and `raster::cellStats` give 0. 

```r
library(terra)
## Warning: package 'terra' was built under R version 4.1.3
## terra 1.5.24
rr <- rast(ncol=100, nrow=100, names="stratum")

rr[] <- NA

global(rr, "sum", na.rm = TRUE)
##         sum
## stratum  NA
raster::cellStats(as(rr, "Raster"), "sum", na.rm = TRUE)
## [1] 0
sum(c(NA, NaN), na.rm = TRUE)
## [1] 0
```

**Comment by rhijmans** [comment]
I think that it makes more sense for `sum(NA, na.rm=TRUE) ` to return `NA` then to return zero. This is especially true if you sum across raster layers by cell. For `global` it matters less. It is true that base R returns zero, and that makes what `terra` does a but surprising (if you aware of it). And you can logically justify this behavior because "the sum of nothing is zero"; but I think it really is a programming artifact, stemming from the output value beging initialized at zero. Consider:

```
sum(NA, na.rm=TRUE) 
#[1] 0
prod(NA, na.rm=TRUE) 
#[1] 1
mean(NA, na.rm=TRUE) 
#[1] NaN
``` 

`prod` returns one because that is how it is initialized (I assume); but the product of nothing is not one. Likewise, if the sum of nothing is zero, then the mean of nothing should also be zero. R returns NaN because it divides the sum by the number of observations (zero). I think it would be more consistent and intuitive if these all returned `NA`. 

For cell-based computations with `terra` you get:

```
library(terra)
r = rast(ncol=10, nrow=10, vals=NA)
s = c(r, r, r)
sum(r, na.rm=T) |> minmax()
#     sum
#[1,] NaN
#[2,] NaN
mean(r, na.rm=T) |> minmax()
#     mean
#[1,]  NaN
#[2,]  NaN
prod(r, na.rm=T) |> minmax()
#     prod
#[1,]  NaN
#[2,]  NaN
``` 

With `global` you get: 

```
global(r, sum, na.rm=T)
#      sum
#lyr.1  NA
global(r, mean, na.rm=T)
#      mean
#lyr.1  NaN
global(r, prod, na.rm=T)
#      global
#lyr.1      1
```

So `prod` behaves differently, because, unlike "sum" and "mean" it uses the R function, not the internal (to terra) function. I am inclined to change that such that it also returns NA or NaN.
