### ISSUE TITLE
aggregate not behaving as expected

### ISSUE THREAD

**Issue by thomarse-ef** [rspatial/terra#605]
I'm having an issue with `terra::aggregate()`, the output isn't correct:

```
library(terra)
library(raster)
x = 1000
y <- rast(nrow=x, ncol=x, res=1, vals = sample(0:1, x, replace = TRUE))
plot(terra::aggregate(y, fact = 100, fun = sum))
# for comparison:
plot(raster::aggregate(raster(y), fact = 100, fun = sum))
```

**Comment by brownag** [comment]
I think you will get the same results if you specify `na.rm=TRUE` to `terra::aggregate()`. 

The default value of this arg is not set in terra, so the default comes from definition of `fun` (for `sum()` default is `FALSE`), whereas in `raster::aggregate()` `na.rm` has default value `TRUE`.

**Comment by thomarse-ef** [comment]
OK thanks, that's fixed it. Not sure I understand how though - there weren't any NA values in my raster (or were there?)

**Comment by brownag** [comment]
I think it must have to do with the resulting dimensions of `y` and using a `fact` of 100.

You specify `nrow`and `ncol` to be 1000 in call to `rast()`, but the resulting raster `y` has dimensions 180x360 due to default longlat CRS that is assigned. Perhaps there is an issue with that constructor?

If you do this then terra and raster work the same:

``` r
library(terra)
library(raster)
x = 1000
y <- rast(matrix(sample(0:1, 1000*1000, replace = TRUE), nrow=x, ncol=x))
plot(terra::aggregate(y, fact = 100, fun = sum, na.rm = TRUE))
```

![](https://i.imgur.com/8JAgvqV.png)

``` r
# for comparison:
plot(raster::aggregate(raster(y), fact = 100, fun = sum))
```

![](https://i.imgur.com/ssgzqk2.png)

**Comment by rhijmans** [comment]
The reason why you do not get 1000 rows and columns with this constructor:

       y <- rast(nrow=x, ncol=x, res=1, vals = sample(0:1, x, replace = TRUE))

is that the values of `nrow` and `ncol` are ignored in favor of the value of `res`.
