### ISSUE TITLE
Overhead in `buffer()`

### ISSUE THREAD

**Issue by kadyb** [rspatial/terra#698]
This is nothing important, but comparing the `terra::buffer()` with the `geos::geos_buffer()` we can see the difference in performance, which can probably be reduced.

```r
library("geos")
library("terra")

n = 50000
x = rnorm(n) * 100
y = rnorm(n) * 100

pts1 = vect(data.frame(x, y), geom = c("x", "y"), crs = "epsg:2180")
pts2 = geos_make_point(x, y, crs = crs(pts1))

t = bench::mark(
  terra = buffer(pts1, 10, quadsegs = 30),
  geos = geos_buffer(pts2, 10, params = geos_buffer_params(quad_segs = 30)),
  iterations = 10, check = FALSE
)
t[, 1:5]
#>   expression      min   median `itr/sec` mem_alloc
#> 1 terra         3.14s    3.22s     0.307      680B
#> 2 geos          1.79s    1.82s     0.546    2.69MB
```

**Comment by rhijmans** [comment]
Thanks for showing this. I am guessing that this is mostly because the geos package stores vectors in an optimal way for GEOS where terra needs to some back and forth. I am sure that the performance of terra could be improved, but that could be very elaborate, and risky (lead to bugs). It is not something I want to undertake in the short term, at least not based on this example.

**Comment by kadyb** [comment]
No problem, thanks for the explanation!
