### ISSUE TITLE
focal3D does not work for any even number of layers

### ISSUE THREAD

**Issue by HemingNM** [rspatial/terra#803]
Hi @rhijmans, 
after correcting #772, focal3D does not work for any even number of layers.
```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
s2 <- s[[1:2]]
s4 <- s[[c(1:3, 1)]]
f <- function(i) c(mean=mean(i), sum=sum(i), min=min(i), max=max(i))
x <- focal3D(s2, c(5, 5, 2), fun=f)
x <- focal3D(s4, c(5, 5, 4), fun=f)
```

**Comment by rhijmans** [comment]
As I pointed out in #722 the window must have odd dimensions. The error message I see when I do 

```
x <- focal3D(s2, c(5, 5, 2), fun=f)
#Error: [focal3D] w must be odd sized in all dimensions
x <- focal3D(s4, c(5, 5, 4), fun=f)
#Error: [focal3D] w must be odd sized in all dimensions
``` 
Also seem pretty clear about that?

**Comment by rhijmans** [comment]
Again, it is not related to the number of layers in the SpatRaster. It is the weights matrix that has to be odd. If you do not want to use some of these weights you can set them to NA.

**Comment by HemingNM** [comment]
Well, then I am missing something important about function usage.
Can you please provide me an example that returns the correct number of layers (i.e. 4) for even layered inputs?
Thank you so much
```
library(terra)
s <- rast(system.file("ex/logo.tif", package="terra"))   
s2 <- s[[1:2]]
s4 <- c(s, s[[1]])
s5 <- c(s, s[[1:2]])

f <- function(i) c(mean=mean(i), sum=sum(i), min=min(i), max=max(i))
x <- focal3D(s, c(5, 5, 3), fun=f)
nlyr(x) # this is what is expected
x <- focal3D(s2, c(5, 5, 3), fun=f)
nlyr(x)
x <- focal3D(s4, c(5, 5, 3), fun=f)
nlyr(x)
x <- focal3D(s5, c(5, 5, 3), fun=f)
nlyr(x)
x <- focal3D(s5, c(5, 5, 5), fun=f)
nlyr(x) # this is what is expected
```

**Comment by rhijmans** [comment]
For example this one: 

```
x <- focal3D(s4, c(5, 5, 3), fun=f)
nlyr(x)
#[1] 8
``` 
I think this is correct because your weights array covers 3 layers (the third dimension). In this case that is only meaningful for the second and third layer as the first and fourth layers only have one neighboring layer. Your function returns four values, so you get 2 x 4 = 8 layers as output.

Unless you use `pad=TRUE` to add virtual layers 

```
x <- focal3D(s4, c(5, 5, 3), fun=f, pad=T)
nlyr(x)
#[1] 16
``` 
Now you have 4 * 4 = 16 layers. In this situation you would want to change the padvalue, or use na.rm-TRUE, otherwise you just add empty layers. Or use expand=TRUE where that makes sense.

That does not work when then the number of layers in the weights array is smaller than the number of layers. 

```
x <- focal3D(s2, c(5, 5, 3), fun=f, pad=T)
#Error: [focal3D] the third weights dimension is larger than nlyr(x)
``` 
And perhaps that is a bug (I am not sure), but it is indeed easy to work around it by adding a layer yourself.
