### ISSUE TITLE
Fastest way to extract data from many rasters

### ISSUE THREAD

**Issue by p-schaefer** [rspatial/terra#852]
I'm working with some pretty large spatial datasets and am struggling to determine the best way of extracting the data I need.  

For context, I'm working on some hydrologically relevant spatial summaries of landscape variables. I'm using the [hydroweight](https://github.com/bkielstr/hydroweight) package to calculate weighting schemes to apply across the landscape. I then have about 140 rasters (numeric ones being about about 2.5GB in size each, and categorical ones about 30MB each) which I would like to apply these spatial weights to, and summarize the results by catchment or sub-catchment polygons.  I've tried a few things to speed this up, including parallel processing, but quickly run into memory limitations. I have over 1000 catchments I'd like to summarize these attributes over. 

So, I have a few questions up front:
- How significant is the overhead for using vsizip? As I keep all the rasters in zip files for ease of data management
- Is it better to store the data as multiple individual rasters, or a single raster with many layers?

An avenue I'm exploring right now is reading the raster values into an SQLite database by cell number, and those cell numbers can then be joined with the relevant catchments and subcatchments. Since SQLite is quite fast, and can calculate the summaries I need directly without pulling the data into R, I thought this would be a good way forward. To facilitate that, I was using multiple cores, each reading in the full layer with `terra::rast()` then using `terra::readStart()` together with `terra::readValues()` to read in chunks of rasters in parallel. These chucks get deposited as .csv files, and a separate processor core is scanning for these csv files and writing them to the SQLite database as they get created. This saves quite a bit of harddrive and memory space. I found this approach faster overall than using `terra::extract()` for the same purpose, and I think its because `terra::extract()` run `terra::readStart()` separately each time it runs.

So a second set of questions I have is:
- Is this a reasonable strategy overall?
- Am I correct in my assumptions about about  `terra::extract()` and  `terra::readStart()`, with  `terra::readStart()` being the bottleneck in extracting values?

Thank you in advance, and I apologize if these are not the easiest questions to answer

**Comment by kadyb** [comment]
I don't have clear answers, but loose ideas that you can check:

1. Test [exactextractr](https://github.com/isciences/exactextractr). There is also the interface in C++.
2. Once you have calculated statistics in table, you can use [data.table](https://github.com/Rdatatable/data.table) instead of data.frame.
3. If the extent of rasters is much larger than the polygons, then you can limit it using [virtual raster](https://rspatial.github.io/terra/reference/vrt.html) and load fewer pixels eventually.

**Comment by rhijmans** [comment]
@kadyb: I think that (3) would only add more overhead. `extract` only reads the values it needs.

**Comment by rhijmans** [comment]
I am not able to provide a definite answer to this. We would need to have a test-case that we can time, and compare with alternative approaches. 

What I do know is that it is inefficient to run `extract<SpatRaster, SpatVector>` many times for the same raster geometry, and the same vector; because the SpatVector (polygons) need to be rasterized every time. Instead, you could use `cells` to get the corresponding cell numbers. But I would first have a look at `zonal`. That would also avoid opening and closing the files many times (whether that is a significant issue or not, I do not know). 

I do not know the cost of using vsizip, and it probably depends on how much the file is compressed, but I suppose you could find out.  I would guess that one multi-layer file is more efficient than many single-layer files, but again, I have no idea how much the benefit might be.

**Comment by kadyb** [comment]
> @kadyb I have tested [exactextractr](https://github.com/isciences/exactextractr), and there is actually no difference in speed vs terra::extract() in run time for extracting raw cell values by polygon.

  I am surprised because I checked it on my three datasets and the difference is several times (3-10). Below is one example. Did I misunderstand something?

<details>
  <summary>Code</summary>

```r
library("terra")
library("exactextractr")

# vector data (5572 features)
brazil = vect("https://geodata.ucdavis.edu/gadm/gadm4.1/kmz/gadm41_BRA_2.kml")
brazil2 = sf::st_as_sf(brazil)

# raster data (4320 x 8640 pixels, 12 layers)
download.file("https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_2.5m_prec.zip",
              "prec_2.5m.zip")
unzip("prec_2.5m.zip", exdir = "prec_2.5m")
f = list.files("prec_2.5m", pattern = "\\.tif$", full.names = TRUE)

prec = rast(f)
## set.values(prec) ## doesn't work in `terra::extract()`

system.time({y = exact_extract(prec, brazil2, progress = FALSE)
             y = do.call("rbind", y)}) # use `data.table::rbindlist()` because this is slow
#> user  system elapsed
#> 5.70    0.25    5.95

system.time({x = extract(prec, brazil)})
#>  user  system elapsed
#> 40.80    8.76   49.67
```

</details>

**Comment by p-schaefer** [comment]
> > Over 20 minutes to just run rast() on the single file
> 
> That should not be the case, especially if you only have 140 layers. Should be done in seconds. What file format are you using? How long does `describe(filename)` take?

Its a geotiff  with `gdal="COMPRESS=NONE"`. I had deleted my single monster raster file, but I'll recreate it and test it tonight.






> > @kadyb I have tested [exactextractr](https://github.com/isciences/exactextractr), and there is actually no difference in speed vs terra::extract() in run time for extracting raw cell values by polygon.
> 
> I am surprised because I checked it on my three datasets and the difference is several times (3-10). Below is one example. Did I misunderstand something? **Edit:** If you use `exact = TRUE` in `terra::extract()` (so the results will be more like `exact_extract()`) the time difference is even bigger.
> 
> Code


Odd, I'll test it again, the differences in my setup, are:
1) the rasters are in a zip file, so I'm reading them in with vsizip
2) my polygons (about 200k of them) are a shape file, not a kmz
3) my rasters dimensions are: 27470 x 26864 and 144 layers

I was using `dplyr::bind_rows` in my testing of the time comparisons, so I'll try `data.table::rbindlist()`

I'll report back once I have done some more testing on my end

**Comment by kadyb** [comment]
There seems to be a problem with vsizip in `terra::extract()`. Could you check if it works better for unpacked files?

```r
f = list.files("prec_2.5m", pattern = "\\.tif$")
f = paste0("/vsizip/C:/Users/Krzysztof/prec_2.5m.zip/", f)
f = f[1:2] # use only 2 layters
prec = rast(f)

system.time({y = exact_extract(prec, brazil2, progress = FALSE)
             y = do.call("rbind", y)})
#> user  system elapsed
#> 5.06    0.06    5.13 

system.time({x = extract(prec, brazil, exact = FALSE)})
#>   user  system elapsed
#> 174.89   13.98  189.10
```

**Comment by rhijmans** [comment]
Thanks @kadyb. I could see how that could happen. For each extraction, terra needs to read a small part of the file. Given that the file is zipped, GDAL cannot just jump to where it needs to start reading values, but instead it needs to read the file until it gets there. In that case, first loading all values into memory (as you were trying to do in #856) might be much more efficient because the file only needs to be read once. I do not know how compression works with the internal algorithms that are supported by GTiff, but I assume that they support efficient seeking of the desired reading position.

**Comment by rhijmans** [comment]
I assume that the use of `vsizip` is the main issue here.
