### ISSUE TITLE
Layers can change each others' datatypes in data-frame subsets

### ISSUE THREAD

**Issue by Kodiologist** [rspatial/terra#865]
```
> r = terra::rast()
> r$i = seq_len(terra::ncell(r))
Warning: [rast] the first raster was empty and was ignored

> str(r[1:5])
'data.frame':   5 obs. of  1 variable:
 $ i: int  1 2 3 4 5
> r$f = rep(factor(c("a", "b")), len = terra::ncell(r))
> str(r[1:5])
'data.frame':   5 obs. of  2 variables:
 $ i: num  1 2 3 4 5
 $ f: Factor w/ 2 levels "a","b": 1 2 1 2 1
> str(r$i[1:5])
'data.frame':   5 obs. of  1 variable:
 $ i: int  1 2 3 4 5
```

Notice how the second `r[1:5]` results in `i` having type `double` ("`num`") rather than `integer`, but this is avoided when you only ask for `i`, as in `r$i[1:5]`.

Also, I wonder if that warning is correct.

**Comment by rhijmans** [comment]
Thanks, if there were factors and integers, the integers were returned as numeric (even though internally they were still integers).

I now get

```
library(terra)
#terra 1.6.33
r <- rast(ncol=3, nrow=3)
r$i <- seq_len(ncell(r))
is.int(r)
#[1] TRUE
str(r[1:3])
#'data.frame':   3 obs. of  1 variable:
# $ i: int  1 2 3
 
r$f <- rep(factor(c("a", "b")), len=ncell(r))
is.int(r)
#[1]  TRUE FALSE
str(r[1:3])
#'data.frame':   3 obs. of  2 variables:
# $ i: num  1 2 3
# $ f: Factor w/ 2 levels "a","b": 1 2 1
```

The warning was correct, in the sense that you were combing an empty layer `lyr.1` with a new layer `i`. You were warned that the first layer, `lyr.1` was removed because it did not have values (either all layers, or none of the layers must have values).

**Comment by Kodiologist** [comment]
It looks like `i` is still coming out `num` in your test. Were you not running the version with your new change?

**Comment by rhijmans** [comment]
Oops. I probably copied part of the output from before I fixed it. I edited my response so that it reflects what I see now.

**Comment by Kodiologist** [comment]
Cool, thanks.
