### ISSUE TITLE
'interpolate' error 'argument "cores" is missing, with no default'

### ISSUE THREAD

**Issue by AMBarbosa** [rspatial/terra#887]
Hello,
Function 'interpolate' was working normally until recently, but now it throws an error, even when runnning the help examples:
```
library(terra)
library(gstat)
library(sp)

data(meuse)
r <- rast(system.file("ex/meuse.tif", package="terra"))

mg <- gstat(id = "zinc", formula = zinc~1, locations = ~x+y, data=meuse)

z <- interpolate(r, mg)
# Error in .runModel(model, fun, xy, 1, const, (na.rm & hv), index, ...) : 
#  argument "cores" is missing, with no default
```
The error occurs also for other types of interpolation in the Examples, e.g. kriging, Tps, etc.

**Comment by rhijmans** [comment]
Hi, thank you very much. This happened because I improved an internal function for `predict` without considering that the function is also used by `interpolate` (and because the relevant examples are in a "dontrun" block to avoid dependencies). It works again, and now `interpolate` can also use multiple cores, as in:

```
z <- interpolate(r, mg, cores=4, cpkgs="gstat")
```
