### ISSUE TITLE
Direct support for sf objects

### ISSUE THREAD

**Issue by Nowosad** [rspatial/terra#89]
Dear @rhijmans,

are there any plans to allow direct use of **sf** objects in **terra**? Right now, it is necessary to convert them to the `SpatVector` class first, which does not seem a big issue for advanced R users, but it is definitely hard to grasp by R novices. It is also hard to teach other people.

I've attached a simple reprex to provide a context.

Best,
Jakub

``` r
# remotes::install_github("rspatial/terra")
# remotes::install_github("Nowosad/spDataLarge")
library(terra)
#> terra version 0.8.9 (beta-release)
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
library(spData)
library(spDataLarge)

nz_elev = rast(nz_elev)

# does not work
ex = extract(nz_elev, nz_height)
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'extract' for signature '"SpatRaster", "sf"'

# works
ex = extract(nz_elev, vect(nz_height))
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded datum Unknown based on GRS80 ellipsoid in CRS definition,
#>  but +towgs84= values preserved
```

<sup>Created on 2020-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rhijmans** [comment]
There are not that many terra methods yet that take vector data arguments, but the number is growing. Would there have to be two methods for all of them? Doing a few for the obvious candidates would perhaps be more confusing. And there are methods that return vector data as well. With `raster` that seemed a bit less problematic because the sp classes were also somewhat "foreign". I can imagine considering this when terra is more stable; but for the time being I probably do not want to commit to it.

**Comment by Nowosad** [comment]
Of course, thanks for the answer @rhijmans.

**Comment by jldupouey** [comment]
While searching on the web, I came to this thread because I had exactly the same question as @Nowosad. Let me expand a bit on the question.

I've been giving a GIS course with R for several years, which I'm currently renewing. I have to select the software packages I teach. I have chosen `sf` for vectors, which seems to be the obvious choice today. For rasters, the `raster` package was dominant until now, so `terra` seemed a natural choice.  And, in fact, it's already a fantastic tool.

But I completely agree with @Nowosad, beginners in spatial data processing are not going to be at all comfortable (to say the least) with the need to convert from `sf` to `SpatVector` to use the `terra` functions. Especially since many other spatial analysis packages already support sf.

It seems to me that `sf` support in `terra` would be interesting in 3 priority cases:

. each time a vector layer is used as input for a `terra` function with the sole purpose of extracting its extent (in `rast` for example);
. in the `rasterize` function;
. and, possibly, for the output of the reverse operation, `extract`.

I believe that the support of sf in terra is a significant lever to allow access to terra to the largest number of people.

**Comment by nickbearman** [comment]
I came across this issue and am in a very similar situation to @jldupouey . I am teaching GIS in R, and `sf` is the obvious vector package, and `terra` is the obvious raster package. Including a `vect()` command is fine for experienced R users, but is another barrier to new users. 

In my example I am trying to do Zonal Statistics, identical to @Nowosad example. 

Given that things have moved on a bit now, since 2020, is direct support for `sf` objects on the horizon? I think this is a key element that will make `terra` easier to teach to people new to GIS. 

To also 'put my money where my mouth is', would you be open to sponsorship / payment to develop this? As Chair of OSGeo:UK this might be something we are interested in sponsoring. This would also be useful for R Spatial's application to be an OSGeo project (which I do need to look at!)

Best wishes,
Nick.

**Comment by rhijmans** [comment]
I still think that it may be better if something *never* works (unless you use `vect()`) than *sometimes*. The difference is probably who gets confused and when. 

Even so, by popular demand, I have now implemented the @jldupouey priorities (some were already there). That is, you can now use an 'sf' object with `ext`, `rast`, `crop`, `extract`, and `rasterize`.  These are probably the main methods that someone using sf may want to use.

@nickbearman thank you very much for your offer. These changes were trivial to make, so no need for support (but there are other opportunities).

**Comment by nickbearman** [comment]
Thanks very much @rhijmans - I appreciated the potential for confusion, but I think this will be really useful for a lot of folk. I will give it a try for my course and let you know. 

You're welcome - if you have something specific, please feel free to check out https://uk.osgeo.org/. There are details on funding requirements there, and previous work OSGeo:UK has funded. Note we would consider R Spatial to be currently applying for OSGeo recognition, so this would qualify I believe. (Ultimately it is not my decision, but I think it meets the criteria).

**Comment by Nowosad** [comment]
Thank you a lot for this change, Robert. 

Related -- I opened a new PR - https://github.com/rspatial/terra/pull/700 - that also exposes the `crs` function for the `sf` objects and adds an option of using `sf` objects as masks. Let me know if I need to change anything.

**Comment by jmburgos** [comment]
> Even so, by popular demand, I have now implemented the @jldupouey priorities (some were already there). That is, you can now use an 'sf' object with `ext`, `rast`, `crop`, `extract`, and `rasterize`. These are probably the main methods that someone using sf may want to use.

Just a heads up, I am using terra 1.6.47 and these changes are not documented yet.  It would be good to mention this in the help files.
