### ISSUE TITLE
Error in .local(x, ...) : unused argument (index = 3)

### ISSUE THREAD

**Issue by Canderson156** [rspatial/terra#908]
I updated terra to version 1.6-41 yesterday. Today, when I tried to load a SpatRaster from an RDS object using the same code I had been using for months, I'm now getting the following error message:

stack_present <- readRDS("R_objects/stack_present.RDS")
Error in .local(x, ...) : unused argument (index = 3)

Any thoughts?

**Comment by rhijmans** [comment]
What exactly was in that RDS file? I asking because with previous versions it was not possible to recover a `SpatRaster` from a RDS (it would had to be a `PackageSpatRaster`.  

Either way, you should be able to get what you had before with 

 ```
x <- base::readRDS("R_objects/stack_present.RDS")
```

But I do not know what triggered that error, and I would appreciate it if you could share the file with me, or let me know what `class(x)` is and what happens next.

**Comment by Canderson156** [comment]
I left out the next line of code:

stack_present <- readRDS("R_objects/stack_present.RDS")
stack_present <- rast(stack_present)

Before today, I was reading in stack_present as a PackedSpatRaster, and then unpacking it in the second line.

Interestingly I tried what you suggested and now am still receiving the error on the second line instead of the first:

> stack_present <- base::readRDS("R_objects/stack_present.RDS")
Error in (function (x)  : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
> stack_present <- base::readRDS("R_objects/stack_present.RDS")
> stack_present <- rast(stack_present)
Error in .local(x, ...) : unused argument (index = 3)

Here is a copy of the file, interested to hear if the same behaviour occurs for you.
https://drive.google.com/drive/folders/1w3OxiWh-7sZtx86aMbbAkSDIt_qVhR3J?usp=sharing

When I create the stack_present.RDS file, I use saveRDS on a SpatRaster, and this would result in a PackedSpatRaster being saved. Is this the appropriate way to save an RDS of a SpatRaster? After having this issue today, I did work on changing my script to avoid using RDS at all as you recommended in the terra help files to avoid having issues like this.

**Comment by rhijmans** [comment]
Thanks for sharing the file. That was a bug related to recovering the categories from a PackedSpatRaster. With the development version. I now see

``` 
library(terra)
r <- readRDS("stack_present.RDS")
r
#class       : SpatRaster 
#dimensions  : 614, 741, 24  (nrow, ncol, nlyr)
#resolution  : 5000, 5000  (x, y)
#extent      : 4222903, 7927903, 2358584, 5428584  (xmin, xmax, ymin, ymax)
#coord. ref. : NAD83 / Statistics Canada Lambert 
#source(s)   : memory
#names       : value, value, mean_~_temp, mean_~est_Q, mean_~est_Q, annua~recip, ... 
#min values  :     1,     2,  -27.118614,   -8.145844,  -42.773540,    62.19235, ... 
#max values  :    20,     9,   -1.187054,   12.149782,   -2.280292,   722.37830, ... 
```

Note that the unwrapping is now done automatically. In previous versions you had to do

```
r <- rast( readRDS("stack_present.RDS") )
```

But you need to avoid that now, because if you do that, you call `rast` on a `SpatRaster` and that returns the raster template (with no cell values)

```
r
#class       : SpatRaster 
#dimensions  : 614, 741, 24  (nrow, ncol, nlyr)
#resolution  : 5000, 5000  (x, y)
#extent      : 4222903, 7927903, 2358584, 5428584  (xmin, xmax, ymin, ymax)
#coord. ref. : NAD83 / Statistics Canada Lambert 
``` 

The current version of "terra" has better support for reading and writing Rds files; as the conversion to and from the PackageSpatRaster is automatic. I still would not generally recommend using that format to store SpatRaster data. Especially not for large datasets.
