### ISSUE TITLE
Error using weighted.mean in tapp

### ISSUE THREAD

**Issue by tber** [rspatial/terra#923]
The code used to work but when I am now trying to calculate weighted annual average values from CMIP6 climate model raster files (1032 bands) I get an error from the weighted.mean function telling me the length of the weights vector does not fit the size of the raster subset.

This is how I define the weights and try to apply the weighed mean function
```
days_in_months <- c(31,28,31,30,31,30,31,31,30,31,30,31)
r_nbp_MPI_ESM_y <- tapp(r_nbp_MPI_ESM, "years", fun=weighted.mean, days_in_months, na.rm=T)
```
r_nbp_MPI_ESM is a SpatRaster:
```
> r_nbp_MPI_ESM
class       : SpatRaster 
dimensions  : 96, 192, 1032  (nrow, ncol, nlyr)
resolution  : 1.875, 1.864677  (x, y)
extent      : -180.9375, 179.0625, -89.50451, 89.50451  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 
source(s)   : memory
names       :         nbp_1,         nbp_2,         nbp_3,         nbp_4,         nbp_5,         nbp_6, ... 
min values  : -6.103042e-08, -4.639188e-08, -4.785456e-08, -7.975401e-08, -6.741537e-08, -6.310805e-08, ... 
max values  :  5.421462e-08,  5.699356e-08,  5.628667e-08,  7.146340e-08,  6.951468e-08,  7.085649e-08, ... 
time (days) : 2015-01-16 to 2100-12-16 
```
The error message is:
```
Error in weighted.mean.default(newX[, i], ...) : 
  'x' and 'w' must have the same length
```

**Comment by rhijmans** [comment]
I think this is a "how to" question, and please stackoverflow.com for these kind of questions. 
I do not think you want to compute the weighted mean, because you do not have weights.
Your example is not reproducible so I cannot be sure what you need, but I think you can do (if r_nbp_MPI_ESM had time stamps)

```
r_nbp_MPI_ESM_y <- tapp(r_nbp_MPI_ESM,  "months",  fun=mean, na.rm=T)
````

Otherwise, if you have a 365-day calendar, you could do 

days_in_months <- c(31,28,31,30,31,30,31,31,30,31,30,31)
idx <- lapply(1:12, \(i) rep(i, days_in_months[i])) |> unlist()

```
r_nbp_MPI_ESM_y <- tapp(r_nbp_MPI_ESM,  idx,  fun=mean, na.rm=T)
````
