### ISSUE TITLE
Error in x@ptr$writeValues(v, start - 1, nrows) :    Not compatible with requested type: [type=list; target=double].

### ISSUE THREAD

**Issue by TianyaImpression** [rspatial/terra#962]
I tried to do multi linear regression for raster layers using terra.

OS: WIN10
R 4.2.2
TERRA 1.6.41

```
library(terra)
library(tidyverse)
ndvilist = list.files(path = "./NDVI/", pattern = ".tif$")
ndvidir = paste0("./NDVI/", ndvilist)
ndvi = rast(ndvidir)

prlist = list.files(path = "./pr/", pattern = ".tif$")
prdir = paste0("./pr/", prlist)
pr = rast(prdir)

sradlist = list.files(path = "./srad/", pattern = ".tif$")
sraddir = paste0("./srad/", sradlist)
srad = rast(sraddir)

taslist = list.files(path = "./tas/", pattern = ".tif$")
tasdir = paste0("./tas/", taslist)
tas = rast(tasdir)

windlist = list.files(path = "./wind/", pattern = ".tif$")
winddir = paste0("./wind/", windlist)
wind = rast(winddir)

lmrast = c(ndvi, pr, srad, tas, wind)
fun_mlr =  function(x){
  if(length(na.omit(x))<95) return(c(NA, NA, NA))
    else {
      lm1 = lm(x[1:19]~x[20:38]+x[39:57]+x[58:76]+x[77:95])
      a1 = summary(lm1)
      a2 = a1$coefficients[2]
      a3 = a1$fstatistic
      pvalue = 1-pf(a3[1], a3[2], a3[3])
      intercept = a1$coefficients[1]
      a_pr = a1$coefficients[2]
      b_srad = a1$coefficients[3]
      c_tas = a1$coefficients[4]
      d_wind = a1$coefficients[5]
      return(c(intercept, a_pr, b_srad, c_tas, d_wind, pvalue))
    }
}

rast_mlr = app(lmrast, fun_mlr, cores=28)
```
it failed. 

I wonder what's wrong. Thank you!

![image](https://user-images.githubusercontent.com/22004043/210172089-7b484f32-d245-412c-b2b6-291943ed7c97.png)

**Comment by rhijmans** [comment]
First some ground rules :

- For "how to" questions like this, please use [stackoverflow](https://stackoverflow.com/) and your question has been asked and answered there. This github site is for bug reports and feature requests.
- Always include a _minimal, self-contained, reproducible example by generate some example data with code, or using a file that ships with R (like in the examples in the manual), and only include calls to `library` that are essential (never use `library(tidyverse)`)
- Do not include screenshots. Copy and paste the text that R returns 

Now the answer to your question:

I think the error you are getting occurs because the length of the below is six

```
 return(c(intercept, a_pr, b_srad, c_tas, d_wind, pvalue))
```

While the length of this is three:

```
return(c(NA, NA, NA))
```
It should be 

```
return(c(NA, NA, NA, NA, NA, NA))
```
