### ISSUE TITLE
Loading terra resets terraOptions()

### ISSUE THREAD

**Issue by gpatoine** [rspatial/terra#995]
I noticed an unexpected behavior, where loading terra resets terraOptions that had been set before. I do not know if this is on purpose, but it worked differently with `raster`. My use case was to set the options in the `.Rprofile` (based on the computer being used), which was quite convenient. I am not sure if this is a recent change.

```
> terra::terraOptions(tempdir = "H:/temp", memfrac = 0.4, memmax = 30)
> terra::terraOptions()
memfrac   : 0.4
tempdir   : H:/temp
datatype  : FLT4S
progress  : 3
todisk    : FALSE
verbose   : FALSE
tolerance : 0.1
memmin    : 1
memmax    : 30
> library(terra)
> terraOptions()
memfrac   : 0.6
tempdir   : C:/Users/username/AppData/Local/Temp/6/RtmpimL6I6
datatype  : FLT4S
progress  : 3
todisk    : FALSE
verbose   : FALSE
tolerance : 0.1
memmin    : 1 
```

**Comment by rhijmans** [comment]
When loading the package the options are not carried over from a previous session, and that would not be desirable. 
But you are right that you could set your own defaults for "raster" by adding them to .Rprofile. I am not a big fan of that because it is just clearer to set things in a script, but I can understand that it can be convenient. The way that the options are handled by "terra" is a bit different, and I will add some code to support loading them from .Rprofile.

**Comment by rhijmans** [comment]
With commit (https://github.com/rspatial/terra/commit/76bdb62260c334304130cb3eb36f259559b77020 ) you can now set options in ".Rprofile.size" like this 

```
options(terra_default=list(tempdir="d:/temp", memfrac=.4))
```
With these default options set,  I get 

```
library(terra)
#terra 1.7.6
terraOptions()
#datatype  : FLT4S
#memfrac   : 0.4
#tolerance : 0.1
#verbose   : FALSE
#verbose   : FALSE
#todisk    : FALSE
#tempdir   : d:/temp
#datatype  : FLT4S
#memmin    : 1
#progress  : 3
```

**Comment by gpatoine** [comment]
Great, thank you for the quick response!
I ❤️ terra.
