### ISSUE TITLE
Possible bug with project

### ISSUE THREAD

**Issue by flottsam** [rspatial/terra#997]
I have hundreds of rasters in various different UTM coordinate systems and various resolutions (mostly 30x30 and 20x20). 
I've projected them all to Albers eq. area (EPSG 5070) using 30x30m resolution. 
Checking the resolution of the output with `cellSize()`, the resolution is 30x30m (min value 900, max value 900).
However, when examining the output in QGIS, I noticed that projecting from 20x20m resulted in a pixel resolution of 30,-30.00000000000029132. 

I realize this is minuscule, but thought it might be a bug. 

Example code: 
```
(r_albs <- project(r, "EPSG:5070", res=30, method="near"))
cellSize(r_albs)
```
Here's a link to an example raster:
https://drive.google.com/drive/folders/1Smqhzd2EG9ksvqAn6Rh9G0f-zKDg_eWm?usp=sharing

(Using terra 1.7-3)

**Comment by kadyb** [comment]
Isn't this problem related to the accuracy of floating point numbers? The difference is small, so it can probably be ignored.

```r
options(digits = 18) # print more decimal digits
res(r_albs)
#> [1] 30.0000000000000000 30.0000000000002913

## (ymax - ymin) / nrow
(1057430.02230030065 - 1045370.02230030054) / 402
#> 30.0000000000002913
```

**Comment by rhijmans** [comment]
The underlying reason is indeed floating point imprecision. You end up with this extent

```
e <- ext(r_albs)
print( as.vector(e), 18)
#                xmin                 xmax                 ymin                 ymax 
#-1463883.46178702102 -1449693.46178702102  1045370.02230030054  1057430.02230030065 
```

And with that many decimals you are likely to get some loss of precision.

The origin of the problem is that you do not specify a template raster to project to. That is ill-advised in most cases,
You can avoid the problem by creating a template raster with an extent that consists of whole numbers. 

```
x <- rast(r_albs)
ext(x) <- floor(e)
res(x) <- 30
print(as.vector(ext(x)), 18)
#    xmin     xmax     ymin     ymax 
#-1463884 -1449694  1045370  1057430 

r_albs2 <- project(r, x, method="near")
print(res(r_albs2), 18)
#[1] 30 30
```

Note that `cellsize` is not the same a `res` (resolution). The x and y spatial resolution are constant in a raster. The actual cellsize *can* vary a lot because of distortion (not with an equal-area projection such as Albers as you are using).
