### ISSUE TITLE
resample() function in R's "terra" library does not work properly in specific situation

### ISSUE THREAD

**Issue by HassanMasoomi** [rspatial/terra#999]
I was trying to resample a high resolution raster into a lower resolution raster using `resample(x, y, method = "sum")`. However, the resampled raster showed NA on some edges.

I posted this [on stackoverflow](https://stackoverflow.com/questions/75339860/resample-function-in-rs-terra-library-does-not-work-properly-in-specific-si/75340091#75340091) but found a workaround for it a bit later. Apparently, if a cell in the low_res raster is not within the extent of the high_res raster, it will get NA value. So, as a solution, I tried adding cells around the high_res raster using extend() (which, I think, the conservative size for extending high_res would be the size of the resolution of low_res raster).

Please for the sample codes and results refer to [here](https://stackoverflow.com/questions/75339860/resample-function-in-rs-terra-library-does-not-work-properly-in-specific-si/75340091#75340091).
Could this be fixed in future versions? Thanks.

**Comment by rhijmans** [comment]
This was fixed [here](https://github.com/OSGeo/gdal/issues/6526) thanks to https://github.com/OSGeo/gdal/issues/6526 
But since the problem originated in GDAL, you need a more recent version thereof. It works fine for me with 

```
library(terra)
gdal()
#[1] "3.6.0"
```

Here is a post about [GDAL versions](https://stackoverflow.com/a/75120294/635245) in R packages.

**Comment by HassanMasoomi** [comment]
Great, thanks.
